# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './interface/tank_cleaning_report_add.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1400, 850)
        MainWindow.setMinimumSize(QtCore.QSize(1400, 850))
        MainWindow.setMaximumSize(QtCore.QSize(1400, 850))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame_aside_menu = QtWidgets.QFrame(self.centralwidget)
        self.frame_aside_menu.setGeometry(QtCore.QRect(0, -10, 251, 861))
        self.frame_aside_menu.setStyleSheet("\n"
"background-color:#2f6d58")
        self.frame_aside_menu.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_aside_menu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_aside_menu.setObjectName("frame_aside_menu")
        self.label_15 = QtWidgets.QLabel(self.frame_aside_menu)
        self.label_15.setGeometry(QtCore.QRect(10, 30, 221, 91))
        self.label_15.setStyleSheet("image: url(:/img/logo_tecsep-1-removebg-preview.png);")
        self.label_15.setText("")
        self.label_15.setObjectName("label_15")
        self.btn_dashboard = QtWidgets.QPushButton(self.frame_aside_menu)
        self.btn_dashboard.setGeometry(QtCore.QRect(30, 140, 191, 41))
        self.btn_dashboard.setStyleSheet("\n"
"\n"
"QPushButton#btn_dashboard{\n"
"\n"
"border:none;\n"
"color:white;\n"
"font-size:18px;\n"
"border-radius: 12px;\n"
"transition: background-color 0.5s ease;\n"
"padding:10px;\n"
"text-align:left;\n"
"}\n"
"\n"
"QPushButton#btn_dashboard:hover{\n"
" background-color: #044e42;\n"
"border-radius: 12px;\n"
"transition: background-color 0.5s ease;\n"
"padding:10px;\n"
"}\n"
"\n"
"QPushButton#btn_dashboard:pressed {\n"
" background-color: #044e42;\n"
"border-radius: 12px;\n"
"background-color: #033029;\n"
"padding:10px;\n"
" }\n"
"\n"
"\n"
"")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("./interface/house-solid.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_dashboard.setIcon(icon)
        self.btn_dashboard.setIconSize(QtCore.QSize(25, 25))
        self.btn_dashboard.setFlat(False)
        self.btn_dashboard.setObjectName("btn_dashboard")
        self.btn_compliance = QtWidgets.QPushButton(self.frame_aside_menu)
        self.btn_compliance.setGeometry(QtCore.QRect(30, 290, 191, 41))
        self.btn_compliance.setStyleSheet("QPushButton#btn_compliance{\n"
"\n"
"border:none;\n"
"color:white;\n"
"font-size:18px;\n"
"border-radius: 12px;\n"
"transition: background-color 0.5s ease;\n"
"text-align:left;\n"
"padding:10px\n"
"}\n"
"\n"
"QPushButton#btn_compliance:hover{\n"
" background-color: #044e42;\n"
"border-radius: 12px;\n"
"transition: background-color 0.5s ease;\n"
"}\n"
"\n"
"QPushButton#btn_compliance:pressed {\n"
" background-color: #044e42;\n"
"border-radius: 12px;\n"
"background-color: #033029;\n"
" }\n"
"")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("./interface/vial-solid.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_compliance.setIcon(icon1)
        self.btn_compliance.setIconSize(QtCore.QSize(25, 25))
        self.btn_compliance.setFlat(False)
        self.btn_compliance.setObjectName("btn_compliance")
        self.btn_wbco = QtWidgets.QPushButton(self.frame_aside_menu)
        self.btn_wbco.setGeometry(QtCore.QRect(30, 340, 191, 41))
        self.btn_wbco.setStyleSheet("QPushButton#btn_wbco{\n"
"\n"
"border:none;\n"
"color:white;\n"
"font-size:18px;\n"
"border-radius: 12px;\n"
"transition: background-color 0.5s ease;\n"
"text-align:left;\n"
"padding:10px;\n"
"}\n"
"\n"
"QPushButton#btn_wbco:hover{\n"
" background-color: #044e42;\n"
"border-radius: 12px;\n"
"transition: background-color 0.5s ease;\n"
"}\n"
"\n"
"QPushButton#btn_wbco:pressed {\n"
" background-color: #044e42;\n"
"border-radius: 12px;\n"
"background-color: #033029;\n"
" }")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("./interface/tools.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_wbco.setIcon(icon2)
        self.btn_wbco.setIconSize(QtCore.QSize(25, 25))
        self.btn_wbco.setFlat(False)
        self.btn_wbco.setObjectName("btn_wbco")
        self.btn_filtration = QtWidgets.QPushButton(self.frame_aside_menu)
        self.btn_filtration.setGeometry(QtCore.QRect(30, 390, 191, 41))
        self.btn_filtration.setStyleSheet("QPushButton#btn_filtration{\n"
"\n"
"border:none;\n"
"color:white;\n"
"font-size:19px;\n"
"border-radius: 12px;\n"
"transition: background-color 0.5s ease;\n"
"text-align:left;\n"
"padding:10px;\n"
"}\n"
"\n"
"QPushButton#btn_filtration:hover{\n"
" background-color: #044e42;\n"
"border-radius: 12px;\n"
"transition: background-color 0.5s ease;\n"
"}\n"
"\n"
"QPushButton#btn_filtration:pressed {\n"
" background-color: #044e42;\n"
"border-radius: 12px;\n"
"background-color: #033029;\n"
" }")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("./interface/oil-well-solid.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_filtration.setIcon(icon3)
        self.btn_filtration.setIconSize(QtCore.QSize(25, 25))
        self.btn_filtration.setFlat(False)
        self.btn_filtration.setObjectName("btn_filtration")
        self.btn_tank_cleaning = QtWidgets.QPushButton(self.frame_aside_menu)
        self.btn_tank_cleaning.setGeometry(QtCore.QRect(30, 440, 191, 41))
        self.btn_tank_cleaning.setStyleSheet("QPushButton#btn_tank_cleaning{\n"
"\n"
"border:none;\n"
"color:white;\n"
"font-size:18px;\n"
"border-radius: 12px;\n"
"transition: background-color 0.5s ease;\n"
"padding:10px;\n"
"text-align:left;\n"
"}\n"
"\n"
"QPushButton#btn_tank_cleaning:hover{\n"
" background-color: #044e42;\n"
"border-radius: 12px;\n"
"transition: background-color 0.5s ease;\n"
"padding:10px;\n"
"}\n"
"\n"
"QPushButton#btn_tank_cleaning:pressed {\n"
" background-color: #044e42;\n"
"border-radius: 12px;\n"
"background-color: #033029;\n"
" }")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("./interface/soap-solid.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_tank_cleaning.setIcon(icon4)
        self.btn_tank_cleaning.setIconSize(QtCore.QSize(25, 25))
        self.btn_tank_cleaning.setFlat(False)
        self.btn_tank_cleaning.setObjectName("btn_tank_cleaning")
        self.btn_user_profile = QtWidgets.QPushButton(self.frame_aside_menu)
        self.btn_user_profile.setGeometry(QtCore.QRect(40, 710, 161, 41))
        self.btn_user_profile.setStyleSheet("QPushButton#btn_user_profile{\n"
"\n"
"border:none;\n"
"color:white;\n"
"font-size:18px;\n"
"border-radius: 12px;\n"
"transition: background-color 0.5s ease;\n"
"padding:10px;\n"
"text-align:left;\n"
"}\n"
"\n"
"QPushButton#btn_user_profile:hover{\n"
" background-color: #044e42;\n"
"border-radius: 12px;\n"
"transition: background-color 0.5s ease;\n"
"padding:10px;\n"
"}\n"
"\n"
"QPushButton#btn_user_profile:pressed {\n"
" background-color: #044e42;\n"
"border-radius: 12px;\n"
"background-color: #033029;\n"
" }")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("./interface/user-solid.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_user_profile.setIcon(icon5)
        self.btn_user_profile.setIconSize(QtCore.QSize(25, 25))
        self.btn_user_profile.setFlat(False)
        self.btn_user_profile.setObjectName("btn_user_profile")
        self.btn_logout = QtWidgets.QPushButton(self.frame_aside_menu)
        self.btn_logout.setGeometry(QtCore.QRect(40, 760, 161, 41))
        self.btn_logout.setStyleSheet("QPushButton#btn_logout{\n"
"\n"
"border:none;\n"
"color:white;\n"
"font-size:18px;\n"
"border-radius: 12px;\n"
"transition: background-color 0.5s ease;\n"
"padding:10px;\n"
"text-align:left;\n"
"}\n"
"\n"
"QPushButton#btn_logout:hover{\n"
" background-color: #044e42;\n"
"border-radius: 12px;\n"
"transition: background-color 0.5s ease;\n"
"padding:10px;\n"
"}\n"
"\n"
"QPushButton#btn_logout:pressed {\n"
" background-color: #044e42;\n"
"border-radius: 12px;\n"
"background-color: #033029;\n"
" }")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("./interface/right-from-bracket-solid.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_logout.setIcon(icon6)
        self.btn_logout.setIconSize(QtCore.QSize(25, 25))
        self.btn_logout.setFlat(False)
        self.btn_logout.setObjectName("btn_logout")
        self.btn_user = QtWidgets.QPushButton(self.frame_aside_menu)
        self.btn_user.setGeometry(QtCore.QRect(30, 190, 191, 41))
        self.btn_user.setStyleSheet("\n"
"\n"
"QPushButton#btn_user{\n"
"\n"
"border:none;\n"
"color:white;\n"
"font-size:18px;\n"
"border-radius: 12px;\n"
"transition: background-color 0.5s ease;\n"
"padding:10px;\n"
"text-align:left;\n"
"}\n"
"\n"
"QPushButton#btn_user:hover{\n"
" background-color: #044e42;\n"
"border-radius: 12px;\n"
"transition: background-color 0.5s ease;\n"
"padding:10px;\n"
"}\n"
"\n"
"QPushButton#btn_user:pressed {\n"
" background-color: #044e42;\n"
"border-radius: 12px;\n"
"background-color: #033029;\n"
"padding:10px;\n"
" }\n"
"\n"
"\n"
"")
        self.btn_user.setIcon(icon5)
        self.btn_user.setIconSize(QtCore.QSize(25, 25))
        self.btn_user.setFlat(False)
        self.btn_user.setObjectName("btn_user")
        self.btn_customer = QtWidgets.QPushButton(self.frame_aside_menu)
        self.btn_customer.setGeometry(QtCore.QRect(30, 240, 191, 41))
        self.btn_customer.setStyleSheet("\n"
"\n"
"QPushButton#btn_customer{\n"
"\n"
"border:none;\n"
"color:white;\n"
"font-size:18px;\n"
"border-radius: 12px;\n"
"transition: background-color 0.5s ease;\n"
"padding:10px;\n"
"text-align:left;\n"
"}\n"
"\n"
"QPushButton#btn_customer:hover{\n"
" background-color: #044e42;\n"
"border-radius: 12px;\n"
"transition: background-color 0.5s ease;\n"
"padding:10px;\n"
"}\n"
"\n"
"QPushButton#btn_customer:pressed {\n"
" background-color: #044e42;\n"
"border-radius: 12px;\n"
"background-color: #033029;\n"
"padding:10px;\n"
" }\n"
"\n"
"\n"
"")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("./interface/user-group-solid.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_customer.setIcon(icon7)
        self.btn_customer.setIconSize(QtCore.QSize(25, 25))
        self.btn_customer.setFlat(False)
        self.btn_customer.setObjectName("btn_customer")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(250, 0, 1151, 861))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(1151, 861))
        self.frame.setMaximumSize(QtCore.QSize(16777215, 861))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.frame.setFont(font)
        self.frame.setStyleSheet("background-color:#eff2f9;\n"
"\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setGeometry(QtCore.QRect(0, 0, 1151, 51))
        self.frame_2.setStyleSheet("background-color:#fff")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.lbl_user_logado = QtWidgets.QLabel(self.frame_2)
        self.lbl_user_logado.setGeometry(QtCore.QRect(1020, 20, 111, 20))
        self.lbl_user_logado.setStyleSheet("")
        self.lbl_user_logado.setObjectName("lbl_user_logado")
        self.img_user_logado = QtWidgets.QPushButton(self.frame_2)
        self.img_user_logado.setGeometry(QtCore.QRect(980, 10, 31, 31))
        self.img_user_logado.setStyleSheet("background-color: #fff;\n"
"border-radius:30px;\n"
"width:30px;\n"
"height:30px;")
        self.img_user_logado.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("./interface/user_dark.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.img_user_logado.setIcon(icon8)
        self.img_user_logado.setIconSize(QtCore.QSize(25, 25))
        self.img_user_logado.setObjectName("img_user_logado")
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setGeometry(QtCore.QRect(0, 50, 1151, 151))
        self.frame_3.setStyleSheet("background-color:#2d6b56;")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.lbl_form_tittle = QtWidgets.QLabel(self.frame_3)
        self.lbl_form_tittle.setGeometry(QtCore.QRect(40, 50, 441, 31))
        self.lbl_form_tittle.setStyleSheet("font-size: 30px;\n"
"color:#fff;")
        self.lbl_form_tittle.setObjectName("lbl_form_tittle")
        self.line = QtWidgets.QFrame(self.frame_3)
        self.line.setGeometry(QtCore.QRect(-10, 0, 21, 151))
        self.line.setStyleSheet("color: rgb(255, 255, 255);\n"
"border-color: rgb(255, 255, 255);")
        self.line.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setObjectName("line")
        self.lbl_form_text = QtWidgets.QLabel(self.frame_3)
        self.lbl_form_text.setGeometry(QtCore.QRect(40, 90, 391, 21))
        self.lbl_form_text.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 9pt \"MS Shell Dlg 2\";")
        self.lbl_form_text.setObjectName("lbl_form_text")
        self.frame_9 = QtWidgets.QFrame(self.frame)
        self.frame_9.setGeometry(QtCore.QRect(-1, 830, 1151, 31))
        self.frame_9.setStyleSheet("background-color:#2d6b56;")
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.line_2 = QtWidgets.QFrame(self.frame)
        self.line_2.setGeometry(QtCore.QRect(-40, 750, 41, 151))
        self.line_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"border-color: rgb(255, 255, 255);")
        self.line_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.frame)
        self.line_3.setGeometry(QtCore.QRect(20, 270, 1071, 20))
        self.line_3.setStyleSheet("color: rgb(255, 255, 255);\n"
"")
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.btn_list_report = QtWidgets.QPushButton(self.frame)
        self.btn_list_report.setGeometry(QtCore.QRect(900, 240, 191, 31))
        self.btn_list_report.setStyleSheet("\n"
"\n"
"QPushButton#btn_list_report{\n"
"\n"
"border:none;\n"
"background-color:#044e42;\n"
"color:white;\n"
"font-size:14px;\n"
"border-radius: 6px;\n"
"transition: background-color 0.5s ease;\n"
"padding:10px;\n"
"text-align:rigth;\n"
"}\n"
"\n"
"QPushButton#btn_list_report:hover{\n"
" background-color: #044e42;\n"
"border-radius: 6px;\n"
"transition: background-color 0.5s ease;\n"
"padding:10px;\n"
"}\n"
"\n"
"QPushButton#btn_list_report:pressed {\n"
" background-color: #044e42;\n"
"border-radius: 6px;\n"
"background-color: #033029;\n"
"padding:10px;\n"
" }\n"
"")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("./interface/../../img/file-lines-solid.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_list_report.setIcon(icon9)
        self.btn_list_report.setObjectName("btn_list_report")
        self.tab_menus_wbco = QtWidgets.QTabWidget(self.frame)
        self.tab_menus_wbco.setGeometry(QtCore.QRect(20, 310, 1081, 501))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.tab_menus_wbco.setFont(font)
        self.tab_menus_wbco.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.tab_menus_wbco.setStyleSheet("    \n"
"            QTabWidget::pane {\n"
"\n"
"                      \n"
"\n"
"            }\n"
"            QTabWidget::tab-bar {\n"
"               \n"
"            }\n"
"            QTabBar::tab {\n"
"                background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                            stop: 0 #044e42, stop: 0.4 #044e42,\n"
"                                            stop: 0.5 #044e42, stop: 1.0 #044e42);\n"
"                border: 6px solid #eff2f9;\n"
"                \n"
"               \n"
"              \n"
"                padding: 8px;\n"
"                color:white;\n"
"                border-top-left-radius:8px;\n"
"                border-top-right-radius:8px;\n"
"            }\n"
"            QTabBar::tab:selected, QTabBar::tab:hover {\n"
"                background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                            stop: 0 #033029, stop: 0.4 #033029,\n"
"                                            stop: 0.5 #033029, stop: 1.0 #033029);\n"
"            }")
        self.tab_menus_wbco.setTabPosition(QtWidgets.QTabWidget.North)
        self.tab_menus_wbco.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tab_menus_wbco.setUsesScrollButtons(True)
        self.tab_menus_wbco.setDocumentMode(False)
        self.tab_menus_wbco.setTabsClosable(False)
        self.tab_menus_wbco.setMovable(False)
        self.tab_menus_wbco.setTabBarAutoHide(False)
        self.tab_menus_wbco.setObjectName("tab_menus_wbco")
        self.tab_report_information = QtWidgets.QWidget()
        self.tab_report_information.setObjectName("tab_report_information")
        self.lbl_customer = QtWidgets.QLabel(self.tab_report_information)
        self.lbl_customer.setGeometry(QtCore.QRect(10, 20, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lbl_customer.setFont(font)
        self.lbl_customer.setStyleSheet("color: rgb(52, 52, 52);")
        self.lbl_customer.setObjectName("lbl_customer")
        self.cbx_customer = QtWidgets.QComboBox(self.tab_report_information)
        self.cbx_customer.setGeometry(QtCore.QRect(10, 50, 491, 41))
        self.cbx_customer.setStyleSheet("\n"
"background-color:#fff;\n"
"border: 1px solid #8ec0af;\n"
"border-radius: 6px")
        self.cbx_customer.setObjectName("cbx_customer")
        self.lbl_well_number = QtWidgets.QLabel(self.tab_report_information)
        self.lbl_well_number.setGeometry(QtCore.QRect(10, 110, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lbl_well_number.setFont(font)
        self.lbl_well_number.setStyleSheet("color: rgb(52, 52, 52);")
        self.lbl_well_number.setObjectName("lbl_well_number")
        self.cbx_well_number = QtWidgets.QComboBox(self.tab_report_information)
        self.cbx_well_number.setGeometry(QtCore.QRect(10, 140, 491, 41))
        self.cbx_well_number.setStyleSheet("\n"
"background-color:#fff;\n"
"border: 1px solid #8ec0af;\n"
"border-radius: 6px")
        self.cbx_well_number.setObjectName("cbx_well_number")
        self.lbl_job_ref = QtWidgets.QLabel(self.tab_report_information)
        self.lbl_job_ref.setGeometry(QtCore.QRect(530, 20, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lbl_job_ref.setFont(font)
        self.lbl_job_ref.setStyleSheet("color: rgb(52, 52, 52);")
        self.lbl_job_ref.setObjectName("lbl_job_ref")
        self.txt_job_ref = QtWidgets.QLineEdit(self.tab_report_information)
        self.txt_job_ref.setGeometry(QtCore.QRect(530, 50, 491, 41))
        self.txt_job_ref.setStyleSheet("QLineEdit{\n"
"\n"
"\n"
"background-color:#fff;\n"
"border: 1px solid #8ec0af;\n"
"border-radius: 6px\n"
"}")
        self.txt_job_ref.setPlaceholderText("")
        self.txt_job_ref.setObjectName("txt_job_ref")
        self.txt_rig_name = QtWidgets.QLineEdit(self.tab_report_information)
        self.txt_rig_name.setGeometry(QtCore.QRect(530, 140, 491, 41))
        self.txt_rig_name.setStyleSheet("QLineEdit{\n"
"\n"
"\n"
"background-color:#fff;\n"
"border: 1px solid #8ec0af;\n"
"border-radius: 6px\n"
"}")
        self.txt_rig_name.setPlaceholderText("")
        self.txt_rig_name.setObjectName("txt_rig_name")
        self.txt_field_location = QtWidgets.QLineEdit(self.tab_report_information)
        self.txt_field_location.setGeometry(QtCore.QRect(530, 230, 491, 41))
        self.txt_field_location.setStyleSheet("QLineEdit{\n"
"\n"
"\n"
"background-color:#fff;\n"
"border: 1px solid #8ec0af;\n"
"border-radius: 6px\n"
"}")
        self.txt_field_location.setPlaceholderText("")
        self.txt_field_location.setObjectName("txt_field_location")
        self.txt_aproved_by = QtWidgets.QLineEdit(self.tab_report_information)
        self.txt_aproved_by.setGeometry(QtCore.QRect(10, 310, 491, 41))
        self.txt_aproved_by.setStyleSheet("QLineEdit{\n"
"\n"
"\n"
"background-color:#fff;\n"
"border: 1px solid #8ec0af;\n"
"border-radius: 6px\n"
"}")
        self.txt_aproved_by.setPlaceholderText("")
        self.txt_aproved_by.setObjectName("txt_aproved_by")
        self.txt_job_type = QtWidgets.QLineEdit(self.tab_report_information)
        self.txt_job_type.setGeometry(QtCore.QRect(530, 320, 491, 41))
        self.txt_job_type.setStyleSheet("QLineEdit{\n"
"\n"
"\n"
"background-color:#fff;\n"
"border: 1px solid #8ec0af;\n"
"border-radius: 6px\n"
"}")
        self.txt_job_type.setPlaceholderText("")
        self.txt_job_type.setObjectName("txt_job_type")
        self.txt_project_description = QtWidgets.QLineEdit(self.tab_report_information)
        self.txt_project_description.setGeometry(QtCore.QRect(530, 400, 491, 41))
        self.txt_project_description.setStyleSheet("QLineEdit{\n"
"\n"
"\n"
"background-color:#fff;\n"
"border: 1px solid #8ec0af;\n"
"border-radius: 6px\n"
"}")
        self.txt_project_description.setText("")
        self.txt_project_description.setPlaceholderText("")
        self.txt_project_description.setObjectName("txt_project_description")
        self.lbl_rig_name = QtWidgets.QLabel(self.tab_report_information)
        self.lbl_rig_name.setGeometry(QtCore.QRect(530, 110, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lbl_rig_name.setFont(font)
        self.lbl_rig_name.setStyleSheet("color: rgb(52, 52, 52);")
        self.lbl_rig_name.setObjectName("lbl_rig_name")
        self.lbl_field_location = QtWidgets.QLabel(self.tab_report_information)
        self.lbl_field_location.setGeometry(QtCore.QRect(530, 200, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lbl_field_location.setFont(font)
        self.lbl_field_location.setStyleSheet("color: rgb(52, 52, 52);")
        self.lbl_field_location.setObjectName("lbl_field_location")
        self.lbl_job_type = QtWidgets.QLabel(self.tab_report_information)
        self.lbl_job_type.setGeometry(QtCore.QRect(530, 290, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lbl_job_type.setFont(font)
        self.lbl_job_type.setStyleSheet("color: rgb(52, 52, 52);")
        self.lbl_job_type.setObjectName("lbl_job_type")
        self.lbl_contacto_7 = QtWidgets.QLabel(self.tab_report_information)
        self.lbl_contacto_7.setGeometry(QtCore.QRect(10, 190, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lbl_contacto_7.setFont(font)
        self.lbl_contacto_7.setStyleSheet("color: rgb(52, 52, 52);")
        self.lbl_contacto_7.setObjectName("lbl_contacto_7")
        self.lbl_approved_by = QtWidgets.QLabel(self.tab_report_information)
        self.lbl_approved_by.setGeometry(QtCore.QRect(10, 280, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lbl_approved_by.setFont(font)
        self.lbl_approved_by.setStyleSheet("color: rgb(52, 52, 52);")
        self.lbl_approved_by.setObjectName("lbl_approved_by")
        self.dateEdit = QtWidgets.QDateEdit(self.tab_report_information)
        self.dateEdit.setGeometry(QtCore.QRect(10, 220, 491, 41))
        self.dateEdit.setStyleSheet("QDateEdit{\n"
"\n"
"background-color:#fff;\n"
"border: 1px solid #8ec0af;\n"
"border-radius: 6px\n"
"\n"
"}")
        self.dateEdit.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.dateEdit.setAccelerated(False)
        self.dateEdit.setCorrectionMode(QtWidgets.QAbstractSpinBox.CorrectToPreviousValue)
        self.dateEdit.setProperty("showGroupSeparator", False)
        self.dateEdit.setObjectName("dateEdit")
        self.lbl_description = QtWidgets.QLabel(self.tab_report_information)
        self.lbl_description.setGeometry(QtCore.QRect(530, 370, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lbl_description.setFont(font)
        self.lbl_description.setStyleSheet("color: rgb(52, 52, 52);")
        self.lbl_description.setObjectName("lbl_description")
        self.btn_next_step_tank_information = QtWidgets.QPushButton(self.tab_report_information)
        self.btn_next_step_tank_information.setGeometry(QtCore.QRect(10, 400, 491, 41))
        self.btn_next_step_tank_information.setStyleSheet("\n"
"\n"
"QPushButton#btn_next_step_tank_information{\n"
"\n"
"border:none;\n"
"background-color:#044e42;\n"
"color:white;\n"
"font-size:14px;\n"
"border-radius: 6px;\n"
"transition: background-color 0.5s ease;\n"
"padding:10px;\n"
"text-align:rigth;\n"
"}\n"
"\n"
"QPushButton#btn_next_step_tank_information:hover{\n"
" background-color: #044e42;\n"
"border-radius: 6px;\n"
"transition: background-color 0.5s ease;\n"
"padding:10px;\n"
"}\n"
"\n"
"QPushButton#btn_next_step_tank_information:pressed {\n"
" background-color: #044e42;\n"
"border-radius: 6px;\n"
"background-color: #033029;\n"
"padding:10px;\n"
" }\n"
"")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("./interface/../../img/check-solid.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_next_step_tank_information.setIcon(icon10)
        self.btn_next_step_tank_information.setObjectName("btn_next_step_tank_information")
        self.lbl_description.raise_()
        self.lbl_approved_by.raise_()
        self.lbl_contacto_7.raise_()
        self.lbl_job_type.raise_()
        self.lbl_field_location.raise_()
        self.lbl_rig_name.raise_()
        self.lbl_customer.raise_()
        self.cbx_customer.raise_()
        self.lbl_well_number.raise_()
        self.cbx_well_number.raise_()
        self.lbl_job_ref.raise_()
        self.txt_job_ref.raise_()
        self.txt_rig_name.raise_()
        self.txt_field_location.raise_()
        self.txt_aproved_by.raise_()
        self.txt_job_type.raise_()
        self.txt_project_description.raise_()
        self.dateEdit.raise_()
        self.btn_next_step_tank_information.raise_()
        self.tab_menus_wbco.addTab(self.tab_report_information, "")
        self.tab_tank = QtWidgets.QWidget()
        self.tab_tank.setObjectName("tab_tank")
        self.btn_next_step_dayshift_activities = QtWidgets.QPushButton(self.tab_tank)
        self.btn_next_step_dayshift_activities.setGeometry(QtCore.QRect(10, 190, 381, 41))
        self.btn_next_step_dayshift_activities.setStyleSheet("\n"
"\n"
"QPushButton#btn_next_step_dayshift_activities{\n"
"\n"
"border:none;\n"
"background-color:#044e42;\n"
"color:white;\n"
"font-size:14px;\n"
"border-radius: 6px;\n"
"transition: background-color 0.5s ease;\n"
"padding:10px;\n"
"text-align:rigth;\n"
"}\n"
"\n"
"QPushButton#btn_next_step_dayshift_activities:hover{\n"
" background-color: #044e42;\n"
"border-radius: 6px;\n"
"transition: background-color 0.5s ease;\n"
"padding:10px;\n"
"}\n"
"\n"
"QPushButton#btn_next_step_dayshift_activities:pressed {\n"
" background-color: #044e42;\n"
"border-radius: 6px;\n"
"background-color: #033029;\n"
"padding:10px;\n"
" }\n"
"")
        self.btn_next_step_dayshift_activities.setIcon(icon10)
        self.btn_next_step_dayshift_activities.setObjectName("btn_next_step_dayshift_activities")
        self.lbl_type_hse_2 = QtWidgets.QLabel(self.tab_tank)
        self.lbl_type_hse_2.setGeometry(QtCore.QRect(10, 100, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lbl_type_hse_2.setFont(font)
        self.lbl_type_hse_2.setStyleSheet("color: rgb(52, 52, 52);")
        self.lbl_type_hse_2.setObjectName("lbl_type_hse_2")
        self.lbl_quantity_hse_2 = QtWidgets.QLabel(self.tab_tank)
        self.lbl_quantity_hse_2.setGeometry(QtCore.QRect(400, 100, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lbl_quantity_hse_2.setFont(font)
        self.lbl_quantity_hse_2.setStyleSheet("color: rgb(52, 52, 52);")
        self.lbl_quantity_hse_2.setObjectName("lbl_quantity_hse_2")
        self.lbl_comments_2 = QtWidgets.QLabel(self.tab_tank)
        self.lbl_comments_2.setGeometry(QtCore.QRect(720, 100, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lbl_comments_2.setFont(font)
        self.lbl_comments_2.setStyleSheet("color: rgb(52, 52, 52);")
        self.lbl_comments_2.setObjectName("lbl_comments_2")
        self.txt_comments_non_produtive_man_3 = QtWidgets.QLineEdit(self.tab_tank)
        self.txt_comments_non_produtive_man_3.setGeometry(QtCore.QRect(10, 130, 381, 41))
        self.txt_comments_non_produtive_man_3.setStyleSheet("QLineEdit{\n"
"\n"
"\n"
"background-color:#fff;\n"
"border: 1px solid #8ec0af;\n"
"border-radius: 6px\n"
"}")
        self.txt_comments_non_produtive_man_3.setPlaceholderText("")
        self.txt_comments_non_produtive_man_3.setObjectName("txt_comments_non_produtive_man_3")
        self.txt_comments_non_produtive_man_4 = QtWidgets.QLineEdit(self.tab_tank)
        self.txt_comments_non_produtive_man_4.setGeometry(QtCore.QRect(400, 130, 311, 41))
        self.txt_comments_non_produtive_man_4.setStyleSheet("QLineEdit{\n"
"\n"
"\n"
"background-color:#fff;\n"
"border: 1px solid #8ec0af;\n"
"border-radius: 6px\n"
"}")
        self.txt_comments_non_produtive_man_4.setPlaceholderText("")
        self.txt_comments_non_produtive_man_4.setObjectName("txt_comments_non_produtive_man_4")
        self.txt_comments_non_produtive_man_5 = QtWidgets.QLineEdit(self.tab_tank)
        self.txt_comments_non_produtive_man_5.setGeometry(QtCore.QRect(720, 130, 351, 41))
        self.txt_comments_non_produtive_man_5.setStyleSheet("QLineEdit{\n"
"\n"
"\n"
"background-color:#fff;\n"
"border: 1px solid #8ec0af;\n"
"border-radius: 6px\n"
"}")
        self.txt_comments_non_produtive_man_5.setPlaceholderText("")
        self.txt_comments_non_produtive_man_5.setObjectName("txt_comments_non_produtive_man_5")
        self.lbl_comments_2.raise_()
        self.lbl_quantity_hse_2.raise_()
        self.lbl_type_hse_2.raise_()
        self.btn_next_step_dayshift_activities.raise_()
        self.txt_comments_non_produtive_man_3.raise_()
        self.txt_comments_non_produtive_man_4.raise_()
        self.txt_comments_non_produtive_man_5.raise_()
        self.tab_menus_wbco.addTab(self.tab_tank, "")
        self.tb_dayshift_activities = QtWidgets.QWidget()
        self.tb_dayshift_activities.setObjectName("tb_dayshift_activities")
        self.lbl_daily_progress = QtWidgets.QLabel(self.tb_dayshift_activities)
        self.lbl_daily_progress.setGeometry(QtCore.QRect(10, 10, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lbl_daily_progress.setFont(font)
        self.lbl_daily_progress.setStyleSheet("color: rgb(52, 52, 52);")
        self.lbl_daily_progress.setObjectName("lbl_daily_progress")
        self.btn_next_step_dayshift_per_person = QtWidgets.QPushButton(self.tb_dayshift_activities)
        self.btn_next_step_dayshift_per_person.setGeometry(QtCore.QRect(10, 410, 491, 41))
        self.btn_next_step_dayshift_per_person.setStyleSheet("\n"
"\n"
"QPushButton#btn_next_step_dayshift_per_person{\n"
"\n"
"border:none;\n"
"background-color:#044e42;\n"
"color:white;\n"
"font-size:14px;\n"
"border-radius: 6px;\n"
"transition: background-color 0.5s ease;\n"
"padding:10px;\n"
"text-align:rigth;\n"
"}\n"
"\n"
"QPushButton#btn_next_step_dayshift_per_person:hover{\n"
" background-color: #044e42;\n"
"border-radius: 6px;\n"
"transition: background-color 0.5s ease;\n"
"padding:10px;\n"
"}\n"
"\n"
"QPushButton#btn_next_step_dayshift_per_person:pressed {\n"
" background-color: #044e42;\n"
"border-radius: 6px;\n"
"background-color: #033029;\n"
"padding:10px;\n"
" }\n"
"")
        self.btn_next_step_dayshift_per_person.setIcon(icon10)
        self.btn_next_step_dayshift_per_person.setObjectName("btn_next_step_dayshift_per_person")
        self.txt_area_daily_progress = QtWidgets.QPlainTextEdit(self.tb_dayshift_activities)
        self.txt_area_daily_progress.setGeometry(QtCore.QRect(10, 40, 1051, 61))
        self.txt_area_daily_progress.setStyleSheet("background-color:#fff;\n"
"border: 1px solid #8ec0af;\n"
"border-radius: 6px")
        self.txt_area_daily_progress.setObjectName("txt_area_daily_progress")
        self.lbl_planned_activities = QtWidgets.QLabel(self.tb_dayshift_activities)
        self.lbl_planned_activities.setGeometry(QtCore.QRect(10, 110, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lbl_planned_activities.setFont(font)
        self.lbl_planned_activities.setStyleSheet("color: rgb(52, 52, 52);")
        self.lbl_planned_activities.setObjectName("lbl_planned_activities")
        self.txt_area_planed_activities = QtWidgets.QPlainTextEdit(self.tb_dayshift_activities)
        self.txt_area_planed_activities.setGeometry(QtCore.QRect(10, 140, 1051, 61))
        self.txt_area_planed_activities.setStyleSheet("background-color:#fff;\n"
"border: 1px solid #8ec0af;\n"
"border-radius: 6px")
        self.txt_area_planed_activities.setObjectName("txt_area_planed_activities")
        self.lbl_norm_reading = QtWidgets.QLabel(self.tb_dayshift_activities)
        self.lbl_norm_reading.setGeometry(QtCore.QRect(10, 210, 331, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lbl_norm_reading.setFont(font)
        self.lbl_norm_reading.setStyleSheet("color: rgb(52, 52, 52);")
        self.lbl_norm_reading.setObjectName("lbl_norm_reading")
        self.txt_area_norm_reading = QtWidgets.QPlainTextEdit(self.tb_dayshift_activities)
        self.txt_area_norm_reading.setGeometry(QtCore.QRect(10, 240, 1051, 61))
        self.txt_area_norm_reading.setStyleSheet("background-color:#fff;\n"
"border: 1px solid #8ec0af;\n"
"border-radius: 6px")
        self.txt_area_norm_reading.setObjectName("txt_area_norm_reading")
        self.lbl_equipament_material = QtWidgets.QLabel(self.tb_dayshift_activities)
        self.lbl_equipament_material.setGeometry(QtCore.QRect(10, 310, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lbl_equipament_material.setFont(font)
        self.lbl_equipament_material.setStyleSheet("color: rgb(52, 52, 52);")
        self.lbl_equipament_material.setObjectName("lbl_equipament_material")
        self.txt_area_equipament_material = QtWidgets.QPlainTextEdit(self.tb_dayshift_activities)
        self.txt_area_equipament_material.setGeometry(QtCore.QRect(10, 340, 1051, 61))
        self.txt_area_equipament_material.setStyleSheet("background-color:#fff;\n"
"border: 1px solid #8ec0af;\n"
"border-radius: 6px")
        self.txt_area_equipament_material.setObjectName("txt_area_equipament_material")
        self.tab_menus_wbco.addTab(self.tb_dayshift_activities, "")
        self.tab_dayshift_per_person = QtWidgets.QWidget()
        self.tab_dayshift_per_person.setObjectName("tab_dayshift_per_person")
        self.lbl_name_person_dayshift = QtWidgets.QLabel(self.tab_dayshift_per_person)
        self.lbl_name_person_dayshift.setGeometry(QtCore.QRect(10, 20, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lbl_name_person_dayshift.setFont(font)
        self.lbl_name_person_dayshift.setStyleSheet("color: rgb(52, 52, 52);")
        self.lbl_name_person_dayshift.setObjectName("lbl_name_person_dayshift")
        self.lbl_trade = QtWidgets.QLabel(self.tab_dayshift_per_person)
        self.lbl_trade.setGeometry(QtCore.QRect(530, 20, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lbl_trade.setFont(font)
        self.lbl_trade.setStyleSheet("color: rgb(52, 52, 52);")
        self.lbl_trade.setObjectName("lbl_trade")
        self.txt_crew_change = QtWidgets.QLineEdit(self.tab_dayshift_per_person)
        self.txt_crew_change.setGeometry(QtCore.QRect(530, 140, 231, 41))
        self.txt_crew_change.setStyleSheet("QLineEdit{\n"
"\n"
"\n"
"background-color:#fff;\n"
"border: 1px solid #8ec0af;\n"
"border-radius: 6px\n"
"}")
        self.txt_crew_change.setPlaceholderText("")
        self.txt_crew_change.setObjectName("txt_crew_change")
        self.cbx_person_dayshift = QtWidgets.QComboBox(self.tab_dayshift_per_person)
        self.cbx_person_dayshift.setGeometry(QtCore.QRect(10, 50, 491, 41))
        self.cbx_person_dayshift.setStyleSheet("\n"
"background-color:#fff;\n"
"border: 1px solid #8ec0af;\n"
"border-radius: 6px")
        self.cbx_person_dayshift.setObjectName("cbx_person_dayshift")
        self.lbl_planed_dembed = QtWidgets.QLabel(self.tab_dayshift_per_person)
        self.lbl_planed_dembed.setGeometry(QtCore.QRect(10, 110, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lbl_planed_dembed.setFont(font)
        self.lbl_planed_dembed.setStyleSheet("color: rgb(52, 52, 52);")
        self.lbl_planed_dembed.setObjectName("lbl_planed_dembed")
        self.lbl_crew_change = QtWidgets.QLabel(self.tab_dayshift_per_person)
        self.lbl_crew_change.setGeometry(QtCore.QRect(530, 110, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lbl_crew_change.setFont(font)
        self.lbl_crew_change.setStyleSheet("color: rgb(52, 52, 52);")
        self.lbl_crew_change.setObjectName("lbl_crew_change")
        self.cbx_trade = QtWidgets.QComboBox(self.tab_dayshift_per_person)
        self.cbx_trade.setGeometry(QtCore.QRect(530, 50, 491, 41))
        self.cbx_trade.setStyleSheet("\n"
"background-color:#fff;\n"
"border: 1px solid #8ec0af;\n"
"border-radius: 6px")
        self.cbx_trade.setObjectName("cbx_trade")
        self.cbx_planned_demeb = QtWidgets.QComboBox(self.tab_dayshift_per_person)
        self.cbx_planned_demeb.setGeometry(QtCore.QRect(10, 140, 491, 41))
        self.cbx_planned_demeb.setStyleSheet("\n"
"background-color:#fff;\n"
"border: 1px solid #8ec0af;\n"
"border-radius: 6px")
        self.cbx_planned_demeb.setObjectName("cbx_planned_demeb")
        self.btn_next_step_hse = QtWidgets.QPushButton(self.tab_dayshift_per_person)
        self.btn_next_step_hse.setGeometry(QtCore.QRect(530, 210, 491, 41))
        self.btn_next_step_hse.setStyleSheet("\n"
"\n"
"QPushButton#btn_next_step_hse{\n"
"\n"
"border:none;\n"
"background-color:#044e42;\n"
"color:white;\n"
"font-size:14px;\n"
"border-radius: 6px;\n"
"transition: background-color 0.5s ease;\n"
"padding:10px;\n"
"text-align:rigth;\n"
"}\n"
"\n"
"QPushButton#btn_next_step_hse:hover{\n"
" background-color: #044e42;\n"
"border-radius: 6px;\n"
"transition: background-color 0.5s ease;\n"
"padding:10px;\n"
"}\n"
"\n"
"QPushButton#btn_next_step_hse:pressed {\n"
" background-color: #044e42;\n"
"border-radius: 6px;\n"
"background-color: #033029;\n"
"padding:10px;\n"
" }\n"
"")
        self.btn_next_step_hse.setIcon(icon10)
        self.btn_next_step_hse.setObjectName("btn_next_step_hse")
        self.btn_add_information_dayshift = QtWidgets.QPushButton(self.tab_dayshift_per_person)
        self.btn_add_information_dayshift.setGeometry(QtCore.QRect(10, 210, 491, 41))
        self.btn_add_information_dayshift.setStyleSheet("\n"
"\n"
"QPushButton#btn_add_information_dayshift{\n"
"\n"
"border:none;\n"
"background-color:#044e42;\n"
"color:white;\n"
"font-size:14px;\n"
"border-radius: 6px;\n"
"transition: background-color 0.5s ease;\n"
"padding:10px;\n"
"text-align:rigth;\n"
"}\n"
"\n"
"QPushButton#btn_add_information_dayshift:hover{\n"
" background-color: #044e42;\n"
"border-radius: 6px;\n"
"transition: background-color 0.5s ease;\n"
"padding:10px;\n"
"}\n"
"\n"
"QPushButton#btn_add_information_dayshift:pressed {\n"
" background-color: #044e42;\n"
"border-radius: 6px;\n"
"background-color: #033029;\n"
"padding:10px;\n"
" }\n"
"")
        self.btn_add_information_dayshift.setIcon(icon10)
        self.btn_add_information_dayshift.setObjectName("btn_add_information_dayshift")
        self.cbx_dayshift = QtWidgets.QComboBox(self.tab_dayshift_per_person)
        self.cbx_dayshift.setGeometry(QtCore.QRect(770, 140, 245, 41))
        self.cbx_dayshift.setStyleSheet("\n"
"background-color:#fff;\n"
"border: 1px solid #8ec0af;\n"
"border-radius: 6px")
        self.cbx_dayshift.setObjectName("cbx_dayshift")
        self.lbl_shift_dayshift = QtWidgets.QLabel(self.tab_dayshift_per_person)
        self.lbl_shift_dayshift.setGeometry(QtCore.QRect(780, 110, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lbl_shift_dayshift.setFont(font)
        self.lbl_shift_dayshift.setStyleSheet("color: rgb(52, 52, 52);")
        self.lbl_shift_dayshift.setObjectName("lbl_shift_dayshift")
        self.lbl_shift_dayshift.raise_()
        self.lbl_planed_dembed.raise_()
        self.lbl_crew_change.raise_()
        self.lbl_name_person_dayshift.raise_()
        self.lbl_trade.raise_()
        self.txt_crew_change.raise_()
        self.cbx_person_dayshift.raise_()
        self.cbx_trade.raise_()
        self.cbx_planned_demeb.raise_()
        self.btn_next_step_hse.raise_()
        self.btn_add_information_dayshift.raise_()
        self.cbx_dayshift.raise_()
        self.tab_menus_wbco.addTab(self.tab_dayshift_per_person, "")
        self.tab_hse = QtWidgets.QWidget()
        self.tab_hse.setObjectName("tab_hse")
        self.lbl_type_hse = QtWidgets.QLabel(self.tab_hse)
        self.lbl_type_hse.setGeometry(QtCore.QRect(10, 80, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lbl_type_hse.setFont(font)
        self.lbl_type_hse.setStyleSheet("color: rgb(52, 52, 52);")
        self.lbl_type_hse.setObjectName("lbl_type_hse")
        self.lbl_comments = QtWidgets.QLabel(self.tab_hse)
        self.lbl_comments.setGeometry(QtCore.QRect(540, 80, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lbl_comments.setFont(font)
        self.lbl_comments.setStyleSheet("color: rgb(52, 52, 52);")
        self.lbl_comments.setObjectName("lbl_comments")
        self.cbx_type_hse = QtWidgets.QComboBox(self.tab_hse)
        self.cbx_type_hse.setGeometry(QtCore.QRect(10, 110, 251, 41))
        self.cbx_type_hse.setStyleSheet("\n"
"background-color:#fff;\n"
"border: 1px solid #8ec0af;\n"
"border-radius: 6px")
        self.cbx_type_hse.setObjectName("cbx_type_hse")
        self.txt_quantity = QtWidgets.QLineEdit(self.tab_hse)
        self.txt_quantity.setGeometry(QtCore.QRect(270, 110, 231, 41))
        self.txt_quantity.setStyleSheet("QLineEdit{\n"
"\n"
"\n"
"background-color:#fff;\n"
"border: 1px solid #8ec0af;\n"
"border-radius: 6px\n"
"}")
        self.txt_quantity.setPlaceholderText("")
        self.txt_quantity.setObjectName("txt_quantity")
        self.lbl_quantity_hse = QtWidgets.QLabel(self.tab_hse)
        self.lbl_quantity_hse.setGeometry(QtCore.QRect(270, 80, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lbl_quantity_hse.setFont(font)
        self.lbl_quantity_hse.setStyleSheet("color: rgb(52, 52, 52);")
        self.lbl_quantity_hse.setObjectName("lbl_quantity_hse")
        self.txt_comments = QtWidgets.QLineEdit(self.tab_hse)
        self.txt_comments.setGeometry(QtCore.QRect(540, 110, 491, 41))
        self.txt_comments.setStyleSheet("QLineEdit{\n"
"\n"
"\n"
"background-color:#fff;\n"
"border: 1px solid #8ec0af;\n"
"border-radius: 6px\n"
"}")
        self.txt_comments.setPlaceholderText("")
        self.txt_comments.setObjectName("txt_comments")
        self.btn_add_information_hse = QtWidgets.QPushButton(self.tab_hse)
        self.btn_add_information_hse.setGeometry(QtCore.QRect(10, 180, 491, 41))
        self.btn_add_information_hse.setStyleSheet("\n"
"\n"
"QPushButton#btn_add_information_hse{\n"
"\n"
"border:none;\n"
"background-color:#044e42;\n"
"color:white;\n"
"font-size:14px;\n"
"border-radius: 6px;\n"
"transition: background-color 0.5s ease;\n"
"padding:10px;\n"
"text-align:rigth;\n"
"}\n"
"\n"
"QPushButton#btn_add_information_hse:hover{\n"
" background-color: #044e42;\n"
"border-radius: 6px;\n"
"transition: background-color 0.5s ease;\n"
"padding:10px;\n"
"}\n"
"\n"
"QPushButton#btn_add_information_hse:pressed {\n"
" background-color: #044e42;\n"
"border-radius: 6px;\n"
"background-color: #033029;\n"
"padding:10px;\n"
" }\n"
"")
        self.btn_add_information_hse.setIcon(icon10)
        self.btn_add_information_hse.setObjectName("btn_add_information_hse")
        self.btn_next_step_produtive_man = QtWidgets.QPushButton(self.tab_hse)
        self.btn_next_step_produtive_man.setGeometry(QtCore.QRect(540, 180, 491, 41))
        self.btn_next_step_produtive_man.setStyleSheet("\n"
"\n"
"QPushButton#btn_next_step_produtive_man{\n"
"\n"
"border:none;\n"
"background-color:#044e42;\n"
"color:white;\n"
"font-size:14px;\n"
"border-radius: 6px;\n"
"transition: background-color 0.5s ease;\n"
"padding:10px;\n"
"text-align:rigth;\n"
"}\n"
"\n"
"QPushButton#btn_next_step_produtive_man:hover{\n"
" background-color: #044e42;\n"
"border-radius: 6px;\n"
"transition: background-color 0.5s ease;\n"
"padding:10px;\n"
"}\n"
"\n"
"QPushButton#btn_next_step_produtive_man:pressed {\n"
" background-color: #044e42;\n"
"border-radius: 6px;\n"
"background-color: #033029;\n"
"padding:10px;\n"
" }\n"
"")
        self.btn_next_step_produtive_man.setIcon(icon10)
        self.btn_next_step_produtive_man.setObjectName("btn_next_step_produtive_man")
        self.lbl_quantity_hse.raise_()
        self.lbl_type_hse.raise_()
        self.lbl_comments.raise_()
        self.cbx_type_hse.raise_()
        self.txt_quantity.raise_()
        self.txt_comments.raise_()
        self.btn_add_information_hse.raise_()
        self.btn_next_step_produtive_man.raise_()
        self.tab_menus_wbco.addTab(self.tab_hse, "")
        self.tab_productive_man_hour = QtWidgets.QWidget()
        self.tab_productive_man_hour.setObjectName("tab_productive_man_hour")
        self.lbl_visual_complete = QtWidgets.QLabel(self.tab_productive_man_hour)
        self.lbl_visual_complete.setGeometry(QtCore.QRect(530, 280, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lbl_visual_complete.setFont(font)
        self.lbl_visual_complete.setStyleSheet("color: rgb(52, 52, 52);")
        self.lbl_visual_complete.setObjectName("lbl_visual_complete")
        self.lbl_original_hour = QtWidgets.QLabel(self.tab_productive_man_hour)
        self.lbl_original_hour.setGeometry(QtCore.QRect(10, 190, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lbl_original_hour.setFont(font)
        self.lbl_original_hour.setStyleSheet("color: rgb(52, 52, 52);")
        self.lbl_original_hour.setObjectName("lbl_original_hour")
        self.txt_booked_today = QtWidgets.QLineEdit(self.tab_productive_man_hour)
        self.txt_booked_today.setGeometry(QtCore.QRect(10, 310, 491, 41))
        self.txt_booked_today.setStyleSheet("QLineEdit{\n"
"\n"
"\n"
"background-color:#fff;\n"
"border: 1px solid #8ec0af;\n"
"border-radius: 6px\n"
"}")
        self.txt_booked_today.setPlaceholderText("")
        self.txt_booked_today.setObjectName("txt_booked_today")
        self.txt_hour_remaining = QtWidgets.QLineEdit(self.tab_productive_man_hour)
        self.txt_hour_remaining.setGeometry(QtCore.QRect(530, 230, 491, 41))
        self.txt_hour_remaining.setStyleSheet("QLineEdit{\n"
"\n"
"\n"
"background-color:#fff;\n"
"border: 1px solid #8ec0af;\n"
"border-radius: 6px\n"
"}")
        self.txt_hour_remaining.setPlaceholderText("")
        self.txt_hour_remaining.setObjectName("txt_hour_remaining")
        self.txt_hour_booked_date = QtWidgets.QLineEdit(self.tab_productive_man_hour)
        self.txt_hour_booked_date.setGeometry(QtCore.QRect(530, 140, 491, 41))
        self.txt_hour_booked_date.setStyleSheet("QLineEdit{\n"
"\n"
"\n"
"background-color:#fff;\n"
"border: 1px solid #8ec0af;\n"
"border-radius: 6px\n"
"}")
        self.txt_hour_booked_date.setPlaceholderText("")
        self.txt_hour_booked_date.setObjectName("txt_hour_booked_date")
        self.lbl_hour_booked_date = QtWidgets.QLabel(self.tab_productive_man_hour)
        self.lbl_hour_booked_date.setGeometry(QtCore.QRect(530, 110, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lbl_hour_booked_date.setFont(font)
        self.lbl_hour_booked_date.setStyleSheet("color: rgb(52, 52, 52);")
        self.lbl_hour_booked_date.setObjectName("lbl_hour_booked_date")
        self.txt_qt_booked_today = QtWidgets.QLineEdit(self.tab_productive_man_hour)
        self.txt_qt_booked_today.setGeometry(QtCore.QRect(530, 50, 491, 41))
        self.txt_qt_booked_today.setStyleSheet("QLineEdit{\n"
"\n"
"\n"
"background-color:#fff;\n"
"border: 1px solid #8ec0af;\n"
"border-radius: 6px\n"
"}")
        self.txt_qt_booked_today.setPlaceholderText("")
        self.txt_qt_booked_today.setObjectName("txt_qt_booked_today")
        self.lbl_description_man_hour = QtWidgets.QLabel(self.tab_productive_man_hour)
        self.lbl_description_man_hour.setGeometry(QtCore.QRect(10, 110, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lbl_description_man_hour.setFont(font)
        self.lbl_description_man_hour.setStyleSheet("color: rgb(52, 52, 52);")
        self.lbl_description_man_hour.setObjectName("lbl_description_man_hour")
        self.lbl_qt_booked_today = QtWidgets.QLabel(self.tab_productive_man_hour)
        self.lbl_qt_booked_today.setGeometry(QtCore.QRect(530, 20, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lbl_qt_booked_today.setFont(font)
        self.lbl_qt_booked_today.setStyleSheet("color: rgb(52, 52, 52);")
        self.lbl_qt_booked_today.setObjectName("lbl_qt_booked_today")
        self.lbl_hour_remaining = QtWidgets.QLabel(self.tab_productive_man_hour)
        self.lbl_hour_remaining.setGeometry(QtCore.QRect(530, 200, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lbl_hour_remaining.setFont(font)
        self.lbl_hour_remaining.setStyleSheet("color: rgb(52, 52, 52);")
        self.lbl_hour_remaining.setObjectName("lbl_hour_remaining")
        self.txt_visual_complete = QtWidgets.QLineEdit(self.tab_productive_man_hour)
        self.txt_visual_complete.setGeometry(QtCore.QRect(530, 310, 491, 41))
        self.txt_visual_complete.setStyleSheet("QLineEdit{\n"
"\n"
"\n"
"background-color:#fff;\n"
"border: 1px solid #8ec0af;\n"
"border-radius: 6px\n"
"}")
        self.txt_visual_complete.setPlaceholderText("")
        self.txt_visual_complete.setObjectName("txt_visual_complete")
        self.lbl_numer_work = QtWidgets.QLabel(self.tab_productive_man_hour)
        self.lbl_numer_work.setGeometry(QtCore.QRect(10, 20, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lbl_numer_work.setFont(font)
        self.lbl_numer_work.setStyleSheet("color: rgb(52, 52, 52);")
        self.lbl_numer_work.setObjectName("lbl_numer_work")
        self.lbl_booked_today = QtWidgets.QLabel(self.tab_productive_man_hour)
        self.lbl_booked_today.setGeometry(QtCore.QRect(10, 280, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lbl_booked_today.setFont(font)
        self.lbl_booked_today.setStyleSheet("color: rgb(52, 52, 52);")
        self.lbl_booked_today.setObjectName("lbl_booked_today")
        self.btn_next_step_non_produtive_man = QtWidgets.QPushButton(self.tab_productive_man_hour)
        self.btn_next_step_non_produtive_man.setGeometry(QtCore.QRect(530, 380, 491, 41))
        self.btn_next_step_non_produtive_man.setStyleSheet("\n"
"\n"
"QPushButton#btn_next_step_non_produtive_man{\n"
"\n"
"border:none;\n"
"background-color:#044e42;\n"
"color:white;\n"
"font-size:14px;\n"
"border-radius: 6px;\n"
"transition: background-color 0.5s ease;\n"
"padding:10px;\n"
"text-align:rigth;\n"
"}\n"
"\n"
"QPushButton#btn_next_step_non_produtive_man:hover{\n"
" background-color: #044e42;\n"
"border-radius: 6px;\n"
"transition: background-color 0.5s ease;\n"
"padding:10px;\n"
"}\n"
"\n"
"QPushButton#btn_next_step_non_produtive_man:pressed {\n"
" background-color: #044e42;\n"
"border-radius: 6px;\n"
"background-color: #033029;\n"
"padding:10px;\n"
" }\n"
"")
        self.btn_next_step_non_produtive_man.setIcon(icon10)
        self.btn_next_step_non_produtive_man.setObjectName("btn_next_step_non_produtive_man")
        self.btn_add_information_productive_man = QtWidgets.QPushButton(self.tab_productive_man_hour)
        self.btn_add_information_productive_man.setGeometry(QtCore.QRect(10, 380, 491, 41))
        self.btn_add_information_productive_man.setStyleSheet("\n"
"\n"
"QPushButton#btn_add_information_productive_man{\n"
"\n"
"border:none;\n"
"background-color:#044e42;\n"
"color:white;\n"
"font-size:14px;\n"
"border-radius: 6px;\n"
"transition: background-color 0.5s ease;\n"
"padding:10px;\n"
"text-align:rigth;\n"
"}\n"
"\n"
"QPushButton#btn_add_information_productive_man:hover{\n"
" background-color: #044e42;\n"
"border-radius: 6px;\n"
"transition: background-color 0.5s ease;\n"
"padding:10px;\n"
"}\n"
"\n"
"QPushButton#btn_add_information_productive_man:pressed {\n"
" background-color: #044e42;\n"
"border-radius: 6px;\n"
"background-color: #033029;\n"
"padding:10px;\n"
" }\n"
"")
        self.btn_add_information_productive_man.setIcon(icon10)
        self.btn_add_information_productive_man.setObjectName("btn_add_information_productive_man")
        self.txt_numbrt_work = QtWidgets.QLineEdit(self.tab_productive_man_hour)
        self.txt_numbrt_work.setGeometry(QtCore.QRect(10, 50, 491, 41))
        self.txt_numbrt_work.setStyleSheet("QLineEdit{\n"
"\n"
"\n"
"background-color:#fff;\n"
"border: 1px solid #8ec0af;\n"
"border-radius: 6px\n"
"}")
        self.txt_numbrt_work.setPlaceholderText("")
        self.txt_numbrt_work.setObjectName("txt_numbrt_work")
        self.txt_description_man_hour = QtWidgets.QLineEdit(self.tab_productive_man_hour)
        self.txt_description_man_hour.setGeometry(QtCore.QRect(10, 140, 491, 41))
        self.txt_description_man_hour.setStyleSheet("QLineEdit{\n"
"\n"
"\n"
"background-color:#fff;\n"
"border: 1px solid #8ec0af;\n"
"border-radius: 6px\n"
"}")
        self.txt_description_man_hour.setPlaceholderText("")
        self.txt_description_man_hour.setObjectName("txt_description_man_hour")
        self.txt_original_hour = QtWidgets.QLineEdit(self.tab_productive_man_hour)
        self.txt_original_hour.setGeometry(QtCore.QRect(10, 220, 491, 41))
        self.txt_original_hour.setStyleSheet("QLineEdit{\n"
"\n"
"\n"
"background-color:#fff;\n"
"border: 1px solid #8ec0af;\n"
"border-radius: 6px\n"
"}")
        self.txt_original_hour.setPlaceholderText("")
        self.txt_original_hour.setObjectName("txt_original_hour")
        self.lbl_booked_today.raise_()
        self.lbl_description_man_hour.raise_()
        self.lbl_hour_remaining.raise_()
        self.lbl_hour_booked_date.raise_()
        self.lbl_qt_booked_today.raise_()
        self.lbl_visual_complete.raise_()
        self.lbl_original_hour.raise_()
        self.txt_booked_today.raise_()
        self.txt_hour_remaining.raise_()
        self.txt_hour_booked_date.raise_()
        self.txt_qt_booked_today.raise_()
        self.txt_visual_complete.raise_()
        self.lbl_numer_work.raise_()
        self.btn_next_step_non_produtive_man.raise_()
        self.btn_add_information_productive_man.raise_()
        self.txt_numbrt_work.raise_()
        self.txt_description_man_hour.raise_()
        self.txt_original_hour.raise_()
        self.tab_menus_wbco.addTab(self.tab_productive_man_hour, "")
        self.tab_non_productive_man_hour = QtWidgets.QWidget()
        self.tab_non_productive_man_hour.setObjectName("tab_non_productive_man_hour")
        self.cbx_non_produtive_man = QtWidgets.QComboBox(self.tab_non_productive_man_hour)
        self.cbx_non_produtive_man.setGeometry(QtCore.QRect(10, 110, 251, 41))
        self.cbx_non_produtive_man.setStyleSheet("\n"
"background-color:#fff;\n"
"border: 1px solid #8ec0af;\n"
"border-radius: 6px")
        self.cbx_non_produtive_man.setObjectName("cbx_non_produtive_man")
        self.txt_comments_non_produtive_man = QtWidgets.QLineEdit(self.tab_non_productive_man_hour)
        self.txt_comments_non_produtive_man.setGeometry(QtCore.QRect(540, 110, 491, 41))
        self.txt_comments_non_produtive_man.setStyleSheet("QLineEdit{\n"
"\n"
"\n"
"background-color:#fff;\n"
"border: 1px solid #8ec0af;\n"
"border-radius: 6px\n"
"}")
        self.txt_comments_non_produtive_man.setPlaceholderText("")
        self.txt_comments_non_produtive_man.setObjectName("txt_comments_non_produtive_man")
        self.txt_quantity_non_produtive_man = QtWidgets.QLineEdit(self.tab_non_productive_man_hour)
        self.txt_quantity_non_produtive_man.setGeometry(QtCore.QRect(270, 110, 231, 41))
        self.txt_quantity_non_produtive_man.setStyleSheet("QLineEdit{\n"
"\n"
"\n"
"background-color:#fff;\n"
"border: 1px solid #8ec0af;\n"
"border-radius: 6px\n"
"}")
        self.txt_quantity_non_produtive_man.setPlaceholderText("")
        self.txt_quantity_non_produtive_man.setObjectName("txt_quantity_non_produtive_man")
        self.btn_next_step_competency = QtWidgets.QPushButton(self.tab_non_productive_man_hour)
        self.btn_next_step_competency.setGeometry(QtCore.QRect(540, 180, 491, 41))
        self.btn_next_step_competency.setStyleSheet("\n"
"\n"
"QPushButton#btn_next_step_competency{\n"
"\n"
"border:none;\n"
"background-color:#044e42;\n"
"color:white;\n"
"font-size:14px;\n"
"border-radius: 6px;\n"
"transition: background-color 0.5s ease;\n"
"padding:10px;\n"
"text-align:rigth;\n"
"}\n"
"\n"
"QPushButton#btn_next_step_competency:hover{\n"
" background-color: #044e42;\n"
"border-radius: 6px;\n"
"transition: background-color 0.5s ease;\n"
"padding:10px;\n"
"}\n"
"\n"
"QPushButton#btn_next_step_competency:pressed {\n"
" background-color: #044e42;\n"
"border-radius: 6px;\n"
"background-color: #033029;\n"
"padding:10px;\n"
" }\n"
"")
        self.btn_next_step_competency.setIcon(icon10)
        self.btn_next_step_competency.setObjectName("btn_next_step_competency")
        self.btn_add_information_non_productive = QtWidgets.QPushButton(self.tab_non_productive_man_hour)
        self.btn_add_information_non_productive.setGeometry(QtCore.QRect(10, 180, 491, 41))
        self.btn_add_information_non_productive.setStyleSheet("\n"
"\n"
"QPushButton#btn_add_information_non_productive{\n"
"\n"
"border:none;\n"
"background-color:#044e42;\n"
"color:white;\n"
"font-size:14px;\n"
"border-radius: 6px;\n"
"transition: background-color 0.5s ease;\n"
"padding:10px;\n"
"text-align:rigth;\n"
"}\n"
"\n"
"QPushButton#btn_add_information_non_productive:hover{\n"
" background-color: #044e42;\n"
"border-radius: 6px;\n"
"transition: background-color 0.5s ease;\n"
"padding:10px;\n"
"}\n"
"\n"
"QPushButton#btn_add_information_non_productive:pressed {\n"
" background-color: #044e42;\n"
"border-radius: 6px;\n"
"background-color: #033029;\n"
"padding:10px;\n"
" }\n"
"")
        self.btn_add_information_non_productive.setIcon(icon10)
        self.btn_add_information_non_productive.setObjectName("btn_add_information_non_productive")
        self.lbl_quantity_non_produtive_man = QtWidgets.QLabel(self.tab_non_productive_man_hour)
        self.lbl_quantity_non_produtive_man.setGeometry(QtCore.QRect(270, 80, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lbl_quantity_non_produtive_man.setFont(font)
        self.lbl_quantity_non_produtive_man.setStyleSheet("color: rgb(52, 52, 52);")
        self.lbl_quantity_non_produtive_man.setObjectName("lbl_quantity_non_produtive_man")
        self.lbl_comments_non_produtive_man = QtWidgets.QLabel(self.tab_non_productive_man_hour)
        self.lbl_comments_non_produtive_man.setGeometry(QtCore.QRect(540, 80, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lbl_comments_non_produtive_man.setFont(font)
        self.lbl_comments_non_produtive_man.setStyleSheet("color: rgb(52, 52, 52);")
        self.lbl_comments_non_produtive_man.setObjectName("lbl_comments_non_produtive_man")
        self.lbl_type_non_produtive_man = QtWidgets.QLabel(self.tab_non_productive_man_hour)
        self.lbl_type_non_produtive_man.setGeometry(QtCore.QRect(10, 80, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lbl_type_non_produtive_man.setFont(font)
        self.lbl_type_non_produtive_man.setStyleSheet("color: rgb(52, 52, 52);")
        self.lbl_type_non_produtive_man.setObjectName("lbl_type_non_produtive_man")
        self.lbl_comments_non_produtive_man.raise_()
        self.lbl_quantity_non_produtive_man.raise_()
        self.lbl_type_non_produtive_man.raise_()
        self.cbx_non_produtive_man.raise_()
        self.txt_comments_non_produtive_man.raise_()
        self.txt_quantity_non_produtive_man.raise_()
        self.btn_next_step_competency.raise_()
        self.btn_add_information_non_productive.raise_()
        self.tab_menus_wbco.addTab(self.tab_non_productive_man_hour, "")
        self.tab_competency_profile = QtWidgets.QWidget()
        self.tab_competency_profile.setObjectName("tab_competency_profile")
        self.lbl_comments_competency = QtWidgets.QLabel(self.tab_competency_profile)
        self.lbl_comments_competency.setGeometry(QtCore.QRect(10, 200, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lbl_comments_competency.setFont(font)
        self.lbl_comments_competency.setStyleSheet("color: rgb(52, 52, 52);")
        self.lbl_comments_competency.setObjectName("lbl_comments_competency")
        self.txt_completed_to_date = QtWidgets.QLineEdit(self.tab_competency_profile)
        self.txt_completed_to_date.setGeometry(QtCore.QRect(530, 150, 491, 41))
        self.txt_completed_to_date.setStyleSheet("QLineEdit{\n"
"\n"
"\n"
"background-color:#fff;\n"
"border: 1px solid #8ec0af;\n"
"border-radius: 6px\n"
"}")
        self.txt_completed_to_date.setPlaceholderText("")
        self.txt_completed_to_date.setObjectName("txt_completed_to_date")
        self.txt_element_completed = QtWidgets.QLineEdit(self.tab_competency_profile)
        self.txt_element_completed.setGeometry(QtCore.QRect(10, 150, 491, 41))
        self.txt_element_completed.setStyleSheet("QLineEdit{\n"
"\n"
"\n"
"background-color:#fff;\n"
"border: 1px solid #8ec0af;\n"
"border-radius: 6px\n"
"}")
        self.txt_element_completed.setPlaceholderText("")
        self.txt_element_completed.setObjectName("txt_element_completed")
        self.txt_unit_completed = QtWidgets.QLineEdit(self.tab_competency_profile)
        self.txt_unit_completed.setGeometry(QtCore.QRect(530, 60, 491, 41))
        self.txt_unit_completed.setStyleSheet("QLineEdit{\n"
"\n"
"\n"
"background-color:#fff;\n"
"border: 1px solid #8ec0af;\n"
"border-radius: 6px\n"
"}")
        self.txt_unit_completed.setPlaceholderText("")
        self.txt_unit_completed.setObjectName("txt_unit_completed")
        self.lbl_completed_to_date = QtWidgets.QLabel(self.tab_competency_profile)
        self.lbl_completed_to_date.setGeometry(QtCore.QRect(530, 120, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lbl_completed_to_date.setFont(font)
        self.lbl_completed_to_date.setStyleSheet("color: rgb(52, 52, 52);")
        self.lbl_completed_to_date.setObjectName("lbl_completed_to_date")
        self.lbl_element_completed = QtWidgets.QLabel(self.tab_competency_profile)
        self.lbl_element_completed.setGeometry(QtCore.QRect(10, 120, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lbl_element_completed.setFont(font)
        self.lbl_element_completed.setStyleSheet("color: rgb(52, 52, 52);")
        self.lbl_element_completed.setObjectName("lbl_element_completed")
        self.lbl_unit_competed = QtWidgets.QLabel(self.tab_competency_profile)
        self.lbl_unit_competed.setGeometry(QtCore.QRect(530, 30, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lbl_unit_competed.setFont(font)
        self.lbl_unit_competed.setStyleSheet("color: rgb(52, 52, 52);")
        self.lbl_unit_competed.setObjectName("lbl_unit_competed")
        self.lbl_name_competency = QtWidgets.QLabel(self.tab_competency_profile)
        self.lbl_name_competency.setGeometry(QtCore.QRect(10, 30, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lbl_name_competency.setFont(font)
        self.lbl_name_competency.setStyleSheet("color: rgb(52, 52, 52);")
        self.lbl_name_competency.setObjectName("lbl_name_competency")
        self.txt_comments_competency = QtWidgets.QLineEdit(self.tab_competency_profile)
        self.txt_comments_competency.setGeometry(QtCore.QRect(10, 230, 491, 41))
        self.txt_comments_competency.setStyleSheet("QLineEdit{\n"
"\n"
"\n"
"background-color:#fff;\n"
"border: 1px solid #8ec0af;\n"
"border-radius: 6px\n"
"}")
        self.txt_comments_competency.setPlaceholderText("")
        self.txt_comments_competency.setObjectName("txt_comments_competency")
        self.btn_add_information_competency = QtWidgets.QPushButton(self.tab_competency_profile)
        self.btn_add_information_competency.setGeometry(QtCore.QRect(530, 230, 491, 41))
        self.btn_add_information_competency.setStyleSheet("\n"
"\n"
"QPushButton#btn_add_information_competency{\n"
"\n"
"border:none;\n"
"background-color:#044e42;\n"
"color:white;\n"
"font-size:14px;\n"
"border-radius: 6px;\n"
"transition: background-color 0.5s ease;\n"
"padding:10px;\n"
"text-align:rigth;\n"
"}\n"
"\n"
"QPushButton#btn_add_information_competency:hover{\n"
" background-color: #044e42;\n"
"border-radius: 6px;\n"
"transition: background-color 0.5s ease;\n"
"padding:10px;\n"
"}\n"
"\n"
"QPushButton#btn_add_information_competency:pressed {\n"
" background-color: #044e42;\n"
"border-radius: 6px;\n"
"background-color: #033029;\n"
"padding:10px;\n"
" }\n"
"")
        self.btn_add_information_competency.setIcon(icon10)
        self.btn_add_information_competency.setObjectName("btn_add_information_competency")
        self.btn_save_report = QtWidgets.QPushButton(self.tab_competency_profile)
        self.btn_save_report.setGeometry(QtCore.QRect(10, 300, 491, 41))
        self.btn_save_report.setStyleSheet("\n"
"\n"
"QPushButton#btn_save_report{\n"
"\n"
"border:none;\n"
"background-color:#044e42;\n"
"color:white;\n"
"font-size:14px;\n"
"border-radius: 6px;\n"
"transition: background-color 0.5s ease;\n"
"padding:10px;\n"
"text-align:rigth;\n"
"}\n"
"\n"
"QPushButton#btn_save_report:hover{\n"
" background-color: #044e42;\n"
"border-radius: 6px;\n"
"transition: background-color 0.5s ease;\n"
"padding:10px;\n"
"}\n"
"\n"
"QPushButton#btn_save_report:pressed {\n"
" background-color: #044e42;\n"
"border-radius: 6px;\n"
"background-color: #033029;\n"
"padding:10px;\n"
" }\n"
"")
        self.btn_save_report.setIcon(icon10)
        self.btn_save_report.setObjectName("btn_save_report")
        self.txt_name_competency_profile = QtWidgets.QLineEdit(self.tab_competency_profile)
        self.txt_name_competency_profile.setGeometry(QtCore.QRect(10, 60, 491, 41))
        self.txt_name_competency_profile.setStyleSheet("QLineEdit{\n"
"\n"
"\n"
"background-color:#fff;\n"
"border: 1px solid #8ec0af;\n"
"border-radius: 6px\n"
"}")
        self.txt_name_competency_profile.setPlaceholderText("")
        self.txt_name_competency_profile.setObjectName("txt_name_competency_profile")
        self.lbl_element_completed.raise_()
        self.lbl_completed_to_date.raise_()
        self.lbl_unit_competed.raise_()
        self.lbl_name_competency.raise_()
        self.lbl_comments_competency.raise_()
        self.txt_completed_to_date.raise_()
        self.txt_element_completed.raise_()
        self.txt_unit_completed.raise_()
        self.txt_comments_competency.raise_()
        self.btn_add_information_competency.raise_()
        self.btn_save_report.raise_()
        self.txt_name_competency_profile.raise_()
        self.tab_menus_wbco.addTab(self.tab_competency_profile, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1400, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        self.tab_menus_wbco.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Dashboard"))
        self.btn_dashboard.setText(_translate("MainWindow", " Dashboard"))
        self.btn_compliance.setText(_translate("MainWindow", " Compliance"))
        self.btn_wbco.setText(_translate("MainWindow", " WBCO Tools"))
        self.btn_filtration.setText(_translate("MainWindow", " Filtration"))
        self.btn_tank_cleaning.setText(_translate("MainWindow", " Tank Cleaning"))
        self.btn_user_profile.setText(_translate("MainWindow", "User Profile"))
        self.btn_logout.setText(_translate("MainWindow", "Logout"))
        self.btn_user.setText(_translate("MainWindow", " Personnel"))
        self.btn_customer.setText(_translate("MainWindow", "Customers"))
        self.lbl_user_logado.setText(_translate("MainWindow", "Victor Manuel"))
        self.lbl_form_tittle.setText(_translate("MainWindow", "Tank Cleaning - Add new Report"))
        self.lbl_form_text.setText(_translate("MainWindow", "Below are the fields to be filled in to generate a new report"))
        self.btn_list_report.setText(_translate("MainWindow", "List all report"))
        self.lbl_customer.setText(_translate("MainWindow", "Customer"))
        self.lbl_well_number.setText(_translate("MainWindow", "Well Number"))
        self.lbl_job_ref.setText(_translate("MainWindow", "Job Ref. Number"))
        self.lbl_rig_name.setText(_translate("MainWindow", "Rig Name"))
        self.lbl_field_location.setText(_translate("MainWindow", "Field/Location"))
        self.lbl_job_type.setText(_translate("MainWindow", "Job Type"))
        self.lbl_contacto_7.setText(_translate("MainWindow", "Report Date"))
        self.lbl_approved_by.setText(_translate("MainWindow", "Approved By"))
        self.lbl_description.setText(_translate("MainWindow", "Project Description"))
        self.btn_next_step_tank_information.setText(_translate("MainWindow", "Next Step"))
        self.tab_menus_wbco.setTabText(self.tab_menus_wbco.indexOf(self.tab_report_information), _translate("MainWindow", "Report Information"))
        self.btn_next_step_dayshift_activities.setText(_translate("MainWindow", "Next Step"))
        self.lbl_type_hse_2.setText(_translate("MainWindow", "Number Tank"))
        self.lbl_quantity_hse_2.setText(_translate("MainWindow", "Type West"))
        self.lbl_comments_2.setText(_translate("MainWindow", "Volume West"))
        self.tab_menus_wbco.setTabText(self.tab_menus_wbco.indexOf(self.tab_tank), _translate("MainWindow", "Tank Information"))
        self.lbl_daily_progress.setText(_translate("MainWindow", "Daily Progress"))
        self.btn_next_step_dayshift_per_person.setText(_translate("MainWindow", "Next Step"))
        self.txt_area_daily_progress.setPlaceholderText(_translate("MainWindow", " Write here..."))
        self.lbl_planned_activities.setText(_translate("MainWindow", "Planned Activites (Next 24hrs)"))
        self.txt_area_planed_activities.setPlaceholderText(_translate("MainWindow", " Write here..."))
        self.lbl_norm_reading.setText(_translate("MainWindow", "NORM Reading result and contamination control"))
        self.txt_area_norm_reading.setPlaceholderText(_translate("MainWindow", " Write here..."))
        self.lbl_equipament_material.setText(_translate("MainWindow", "Equipament Material"))
        self.txt_area_equipament_material.setPlaceholderText(_translate("MainWindow", " Write here..."))
        self.tab_menus_wbco.setTabText(self.tab_menus_wbco.indexOf(self.tb_dayshift_activities), _translate("MainWindow", "Dayshift Activities"))
        self.lbl_name_person_dayshift.setText(_translate("MainWindow", "Name"))
        self.lbl_trade.setText(_translate("MainWindow", "Trade"))
        self.lbl_planed_dembed.setText(_translate("MainWindow", "Planned Demeb"))
        self.lbl_crew_change.setText(_translate("MainWindow", "Crew Change"))
        self.btn_next_step_hse.setText(_translate("MainWindow", "Next Step"))
        self.btn_add_information_dayshift.setText(_translate("MainWindow", "Add the filled information to report"))
        self.lbl_shift_dayshift.setText(_translate("MainWindow", "Shift"))
        self.tab_menus_wbco.setTabText(self.tab_menus_wbco.indexOf(self.tab_dayshift_per_person), _translate("MainWindow", "Dayshift per person"))
        self.lbl_type_hse.setText(_translate("MainWindow", "Type"))
        self.lbl_comments.setText(_translate("MainWindow", "Comments"))
        self.lbl_quantity_hse.setText(_translate("MainWindow", "Quantity"))
        self.btn_add_information_hse.setText(_translate("MainWindow", "Add the filled information to report"))
        self.btn_next_step_produtive_man.setText(_translate("MainWindow", "Next Step"))
        self.tab_menus_wbco.setTabText(self.tab_menus_wbco.indexOf(self.tab_hse), _translate("MainWindow", "HSE(updated daily)"))
        self.lbl_visual_complete.setText(_translate("MainWindow", "Visual  Complete %"))
        self.lbl_original_hour.setText(_translate("MainWindow", "Original Hours Estimated"))
        self.lbl_hour_booked_date.setText(_translate("MainWindow", "Hours Booked To Date"))
        self.lbl_description_man_hour.setText(_translate("MainWindow", "Description"))
        self.lbl_qt_booked_today.setText(_translate("MainWindow", "Q/T Booked Today"))
        self.lbl_hour_remaining.setText(_translate("MainWindow", "Hours Remainig"))
        self.lbl_numer_work.setText(_translate("MainWindow", "Work Order Number"))
        self.lbl_booked_today.setText(_translate("MainWindow", "Hours Booked Today"))
        self.btn_next_step_non_produtive_man.setText(_translate("MainWindow", "Next Step"))
        self.btn_add_information_productive_man.setText(_translate("MainWindow", "Add the filled information to report"))
        self.tab_menus_wbco.setTabText(self.tab_menus_wbco.indexOf(self.tab_productive_man_hour), _translate("MainWindow", "Productive Man Hour "))
        self.btn_next_step_competency.setText(_translate("MainWindow", "Next Step"))
        self.btn_add_information_non_productive.setText(_translate("MainWindow", "Add the filled information to report"))
        self.lbl_quantity_non_produtive_man.setText(_translate("MainWindow", "Quantity"))
        self.lbl_comments_non_produtive_man.setText(_translate("MainWindow", "Comments"))
        self.lbl_type_non_produtive_man.setText(_translate("MainWindow", "Type"))
        self.tab_menus_wbco.setTabText(self.tab_menus_wbco.indexOf(self.tab_non_productive_man_hour), _translate("MainWindow", "Non Prod Man Hour "))
        self.lbl_comments_competency.setText(_translate("MainWindow", "Comments"))
        self.lbl_completed_to_date.setText(_translate("MainWindow", "% Completed to Date"))
        self.lbl_element_completed.setText(_translate("MainWindow", "Element completed"))
        self.lbl_unit_competed.setText(_translate("MainWindow", "Unit completed"))
        self.lbl_name_competency.setText(_translate("MainWindow", "Name"))
        self.btn_add_information_competency.setText(_translate("MainWindow", "Add the filled information to report"))
        self.btn_save_report.setText(_translate("MainWindow", "Save Report"))
        self.tab_menus_wbco.setTabText(self.tab_menus_wbco.indexOf(self.tab_competency_profile), _translate("MainWindow", "Competency Profiles"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
