# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\compliance_avarange_wet.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 320)
        MainWindow.setMinimumSize(QtCore.QSize(1000, 320))
        MainWindow.setMaximumSize(QtCore.QSize(1000, 320))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 1171, 861))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(1151, 861))
        self.frame.setMaximumSize(QtCore.QSize(16777215, 861))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.frame.setFont(font)
        self.frame.setAutoFillBackground(False)
        self.frame.setStyleSheet("background-color:#eff2f9;\n"
"\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setGeometry(QtCore.QRect(0, 0, 1151, 51))
        self.frame_2.setStyleSheet("background-color:#fff")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.img_user_logado = QtWidgets.QPushButton(self.frame_2)
        self.img_user_logado.setGeometry(QtCore.QRect(980, 10, 31, 31))
        self.img_user_logado.setStyleSheet("background-color: #fff;\n"
"border-radius:30px;\n"
"width:30px;\n"
"height:30px;")
        self.img_user_logado.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(".\\user_dark.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.img_user_logado.setIcon(icon)
        self.img_user_logado.setIconSize(QtCore.QSize(25, 25))
        self.img_user_logado.setObjectName("img_user_logado")
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setGeometry(QtCore.QRect(0, 20, 1151, 111))
        self.frame_3.setStyleSheet("background-color:#2d6b56;")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.lbl_form_tittle = QtWidgets.QLabel(self.frame_3)
        self.lbl_form_tittle.setGeometry(QtCore.QRect(40, 20, 391, 41))
        self.lbl_form_tittle.setStyleSheet("font-size: 30px;\n"
"color:#fff;")
        self.lbl_form_tittle.setObjectName("lbl_form_tittle")
        self.line = QtWidgets.QFrame(self.frame_3)
        self.line.setGeometry(QtCore.QRect(-10, 0, 21, 151))
        self.line.setStyleSheet("color: rgb(255, 255, 255);\n"
"border-color: rgb(255, 255, 255);")
        self.line.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setObjectName("line")
        self.lbl_form_text = QtWidgets.QLabel(self.frame_3)
        self.lbl_form_text.setGeometry(QtCore.QRect(40, 60, 391, 21))
        self.lbl_form_text.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 9pt \"MS Shell Dlg 2\";")
        self.lbl_form_text.setObjectName("lbl_form_text")
        self.frame_9 = QtWidgets.QFrame(self.frame)
        self.frame_9.setGeometry(QtCore.QRect(-1, 830, 1151, 31))
        self.frame_9.setStyleSheet("background-color:#2d6b56;")
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.line_2 = QtWidgets.QFrame(self.frame)
        self.line_2.setGeometry(QtCore.QRect(-40, 750, 41, 151))
        self.line_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"border-color: rgb(255, 255, 255);")
        self.line_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setObjectName("line_2")
        self.lbl_wsg = QtWidgets.QLabel(self.frame)
        self.lbl_wsg.setGeometry(QtCore.QRect(10, 160, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lbl_wsg.setFont(font)
        self.lbl_wsg.setStyleSheet("color: red;")
        self.lbl_wsg.setObjectName("lbl_wsg")
        self.txt_wsg = QtWidgets.QLineEdit(self.frame)
        self.txt_wsg.setGeometry(QtCore.QRect(10, 190, 321, 41))
        self.txt_wsg.setStyleSheet("QLineEdit{\n"
"\n"
"\n"
"background-color:#fff;\n"
"border: 1px solid #8ec0af;\n"
"border-radius: 6px\n"
"}")
        self.txt_wsg.setPlaceholderText("")
        self.txt_wsg.setObjectName("txt_wsg")
        self.txt_wocg = QtWidgets.QLineEdit(self.frame)
        self.txt_wocg.setGeometry(QtCore.QRect(340, 190, 321, 41))
        self.txt_wocg.setStyleSheet("QLineEdit{\n"
"\n"
"\n"
"background-color:#fff;\n"
"border: 1px solid #8ec0af;\n"
"border-radius: 6px\n"
"}")
        self.txt_wocg.setPlaceholderText("")
        self.txt_wocg.setObjectName("txt_wocg")
        self.lbl_wocg = QtWidgets.QLabel(self.frame)
        self.lbl_wocg.setGeometry(QtCore.QRect(340, 160, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lbl_wocg.setFont(font)
        self.lbl_wocg.setStyleSheet("color: red;")
        self.lbl_wocg.setObjectName("lbl_wocg")
        self.btn_add_average_dry_cutting = QtWidgets.QPushButton(self.frame)
        self.btn_add_average_dry_cutting.setGeometry(QtCore.QRect(10, 240, 321, 41))
        self.btn_add_average_dry_cutting.setStyleSheet("\n"
"\n"
"QPushButton#btn_add_average_dry_cutting{\n"
"\n"
"border:none;\n"
"background-color:#044e42;\n"
"color:white;\n"
"font-size:14px;\n"
"border-radius: 6px;\n"
"transition: background-color 0.5s ease;\n"
"padding:10px;\n"
"text-align:rigth;\n"
"}\n"
"\n"
"QPushButton#btn_add_average_dry_cutting:hover{\n"
" background-color: #044e42;\n"
"border-radius: 6px;\n"
"transition: background-color 0.5s ease;\n"
"padding:10px;\n"
"}\n"
"\n"
"QPushButton#btn_add_average_dry_cutting:pressed {\n"
" background-color: #044e42;\n"
"border-radius: 6px;\n"
"background-color: #033029;\n"
"padding:10px;\n"
" }\n"
"")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(".\\../../img/check-solid.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_add_average_dry_cutting.setIcon(icon1)
        self.btn_add_average_dry_cutting.setObjectName("btn_add_average_dry_cutting")
        self.lbl_wocg_2 = QtWidgets.QLabel(self.frame)
        self.lbl_wocg_2.setGeometry(QtCore.QRect(670, 160, 291, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lbl_wocg_2.setFont(font)
        self.lbl_wocg_2.setStyleSheet("color: red;")
        self.lbl_wocg_2.setObjectName("lbl_wocg_2")
        self.txt_wocg_2 = QtWidgets.QLineEdit(self.frame)
        self.txt_wocg_2.setGeometry(QtCore.QRect(670, 190, 321, 41))
        self.txt_wocg_2.setStyleSheet("QLineEdit{\n"
"\n"
"\n"
"background-color:#fff;\n"
"border: 1px solid #8ec0af;\n"
"border-radius: 6px\n"
"}")
        self.txt_wocg_2.setPlaceholderText("")
        self.txt_wocg_2.setObjectName("txt_wocg_2")
        self.lbl_wocg.raise_()
        self.lbl_wsg.raise_()
        self.frame_2.raise_()
        self.frame_3.raise_()
        self.frame_9.raise_()
        self.line_2.raise_()
        self.txt_wsg.raise_()
        self.txt_wocg.raise_()
        self.btn_add_average_dry_cutting.raise_()
        self.lbl_wocg_2.raise_()
        self.txt_wocg_2.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1000, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Dashboard"))
        self.lbl_form_tittle.setText(_translate("MainWindow", "Average wet cuttings gms/Kg"))
        self.lbl_form_text.setText(_translate("MainWindow", "Fill in the fields to obtain the sample results"))
        self.lbl_wsg.setText(_translate("MainWindow", "Weight of Sample gms"))
        self.lbl_wocg.setText(_translate("MainWindow", "Weight Oil - calc gms"))
        self.btn_add_average_dry_cutting.setText(_translate("MainWindow", " Add Sample"))
        self.lbl_wocg_2.setText(_translate("MainWindow", "OOC, Weight of Oil on Wet Cuttings gms/kg"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
