# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\compliance_avarange.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1050, 870)
        MainWindow.setMinimumSize(QtCore.QSize(1050, 870))
        MainWindow.setMaximumSize(QtCore.QSize(1050, 870))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 1050, 861))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(1050, 861))
        self.frame.setMaximumSize(QtCore.QSize(1050, 861))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.frame.setFont(font)
        self.frame.setAutoFillBackground(False)
        self.frame.setStyleSheet("background-color:#eff2f9;\n"
"\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setGeometry(QtCore.QRect(0, 0, 1201, 51))
        self.frame_2.setStyleSheet("background-color:#fff")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.img_user_logado = QtWidgets.QPushButton(self.frame_2)
        self.img_user_logado.setGeometry(QtCore.QRect(980, 10, 31, 31))
        self.img_user_logado.setStyleSheet("background-color: #fff;\n"
"border-radius:30px;\n"
"width:30px;\n"
"height:30px;")
        self.img_user_logado.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(".\\user_dark.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.img_user_logado.setIcon(icon)
        self.img_user_logado.setIconSize(QtCore.QSize(25, 25))
        self.img_user_logado.setObjectName("img_user_logado")
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setGeometry(QtCore.QRect(0, 20, 1201, 71))
        self.frame_3.setStyleSheet("background-color:#2d6b56;")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.lbl_form_tittle = QtWidgets.QLabel(self.frame_3)
        self.lbl_form_tittle.setGeometry(QtCore.QRect(40, 0, 391, 41))
        self.lbl_form_tittle.setStyleSheet("font-size: 30px;\n"
"color:#fff;")
        self.lbl_form_tittle.setObjectName("lbl_form_tittle")
        self.line = QtWidgets.QFrame(self.frame_3)
        self.line.setGeometry(QtCore.QRect(-10, 0, 21, 151))
        self.line.setStyleSheet("color: rgb(255, 255, 255);\n"
"border-color: rgb(255, 255, 255);")
        self.line.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setObjectName("line")
        self.lbl_form_text = QtWidgets.QLabel(self.frame_3)
        self.lbl_form_text.setGeometry(QtCore.QRect(40, 40, 391, 21))
        self.lbl_form_text.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 9pt \"MS Shell Dlg 2\";")
        self.lbl_form_text.setObjectName("lbl_form_text")
        self.frame_9 = QtWidgets.QFrame(self.frame)
        self.frame_9.setGeometry(QtCore.QRect(-1, 830, 1151, 31))
        self.frame_9.setStyleSheet("background-color:#2d6b56;")
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.line_2 = QtWidgets.QFrame(self.frame)
        self.line_2.setGeometry(QtCore.QRect(-40, 750, 41, 151))
        self.line_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"border-color: rgb(255, 255, 255);")
        self.line_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setObjectName("line_2")
        self.lbl_weigth_cb_sample_gms = QtWidgets.QLabel(self.frame)
        self.lbl_weigth_cb_sample_gms.setGeometry(QtCore.QRect(10, 100, 311, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lbl_weigth_cb_sample_gms.setFont(font)
        self.lbl_weigth_cb_sample_gms.setStyleSheet("color: rgb(52, 52, 52);")
        self.lbl_weigth_cb_sample_gms.setObjectName("lbl_weigth_cb_sample_gms")
        self.txt_wfrcb_sample_gms = QtWidgets.QLineEdit(self.frame)
        self.txt_wfrcb_sample_gms.setGeometry(QtCore.QRect(10, 130, 321, 41))
        self.txt_wfrcb_sample_gms.setStyleSheet("QLineEdit{\n"
"\n"
"\n"
"background-color:#fff;\n"
"border: 1px solid #8ec0af;\n"
"border-radius: 6px\n"
"}")
        self.txt_wfrcb_sample_gms.setPlaceholderText("")
        self.txt_wfrcb_sample_gms.setObjectName("txt_wfrcb_sample_gms")
        self.txt_wercb = QtWidgets.QLineEdit(self.frame)
        self.txt_wercb.setGeometry(QtCore.QRect(340, 130, 321, 41))
        self.txt_wercb.setStyleSheet("QLineEdit{\n"
"\n"
"\n"
"background-color:#fff;\n"
"border: 1px solid #8ec0af;\n"
"border-radius: 6px\n"
"}")
        self.txt_wercb.setPlaceholderText("")
        self.txt_wercb.setObjectName("txt_wercb")
        self.lbl_wercb = QtWidgets.QLabel(self.frame)
        self.lbl_wercb.setGeometry(QtCore.QRect(340, 100, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lbl_wercb.setFont(font)
        self.lbl_wercb.setStyleSheet("color: rgb(52, 52, 52);")
        self.lbl_wercb.setObjectName("lbl_wercb")
        self.lbl_wsg = QtWidgets.QLabel(self.frame)
        self.lbl_wsg.setGeometry(QtCore.QRect(670, 100, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lbl_wsg.setFont(font)
        self.lbl_wsg.setStyleSheet("color: black;")
        self.lbl_wsg.setObjectName("lbl_wsg")
        self.txt_wsg = QtWidgets.QLineEdit(self.frame)
        self.txt_wsg.setGeometry(QtCore.QRect(670, 130, 351, 41))
        self.txt_wsg.setStyleSheet("QLineEdit{\n"
"\n"
"\n"
"background-color:#fff;\n"
"border: 1px solid #8ec0af;\n"
"border-radius: 6px\n"
"}")
        self.txt_wsg.setPlaceholderText("")
        self.txt_wsg.setObjectName("txt_wsg")
        self.txt_wfrcbsw = QtWidgets.QLineEdit(self.frame)
        self.txt_wfrcbsw.setGeometry(QtCore.QRect(10, 210, 321, 41))
        self.txt_wfrcbsw.setStyleSheet("QLineEdit{\n"
"\n"
"\n"
"background-color:#fff;\n"
"border: 1px solid #8ec0af;\n"
"border-radius: 6px\n"
"}")
        self.txt_wfrcbsw.setPlaceholderText("")
        self.txt_wfrcbsw.setObjectName("txt_wfrcbsw")
        self.lbl_wfrcbswg = QtWidgets.QLabel(self.frame)
        self.lbl_wfrcbswg.setGeometry(QtCore.QRect(10, 180, 311, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lbl_wfrcbswg.setFont(font)
        self.lbl_wfrcbswg.setStyleSheet("color: rgb(52, 52, 52);")
        self.lbl_wfrcbswg.setObjectName("lbl_wfrcbswg")
        self.txt_wwag = QtWidgets.QLineEdit(self.frame)
        self.txt_wwag.setGeometry(QtCore.QRect(340, 210, 371, 41))
        self.txt_wwag.setStyleSheet("QLineEdit{\n"
"\n"
"\n"
"background-color:#fff;\n"
"border: 1px solid #8ec0af;\n"
"border-radius: 6px\n"
"}")
        self.txt_wwag.setPlaceholderText("")
        self.txt_wwag.setObjectName("txt_wwag")
        self.lbl_wwag = QtWidgets.QLabel(self.frame)
        self.lbl_wwag.setGeometry(QtCore.QRect(340, 180, 371, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lbl_wwag.setFont(font)
        self.lbl_wwag.setStyleSheet("color: black;")
        self.lbl_wwag.setObjectName("lbl_wwag")
        self.txt_vwgcm = QtWidgets.QLineEdit(self.frame)
        self.txt_vwgcm.setGeometry(QtCore.QRect(720, 210, 301, 41))
        self.txt_vwgcm.setStyleSheet("QLineEdit{\n"
"\n"
"\n"
"background-color:#fff;\n"
"border: 1px solid #8ec0af;\n"
"border-radius: 6px\n"
"}")
        self.txt_vwgcm.setPlaceholderText("")
        self.txt_vwgcm.setObjectName("txt_vwgcm")
        self.lbl_vwgcm = QtWidgets.QLabel(self.frame)
        self.lbl_vwgcm.setGeometry(QtCore.QRect(720, 180, 281, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lbl_vwgcm.setFont(font)
        self.lbl_vwgcm.setStyleSheet("color: black;")
        self.lbl_vwgcm.setObjectName("lbl_vwgcm")
        self.txt_wgccg = QtWidgets.QLineEdit(self.frame)
        self.txt_wgccg.setGeometry(QtCore.QRect(10, 290, 321, 41))
        self.txt_wgccg.setStyleSheet("QLineEdit{\n"
"\n"
"\n"
"background-color:#fff;\n"
"border: 1px solid #8ec0af;\n"
"border-radius: 6px\n"
"}")
        self.txt_wgccg.setPlaceholderText("")
        self.txt_wgccg.setObjectName("txt_wgccg")
        self.txt_wgceg = QtWidgets.QLineEdit(self.frame)
        self.txt_wgceg.setGeometry(QtCore.QRect(340, 290, 331, 41))
        self.txt_wgceg.setStyleSheet("QLineEdit{\n"
"\n"
"\n"
"background-color:#fff;\n"
"border: 1px solid #8ec0af;\n"
"border-radius: 6px\n"
"}")
        self.txt_wgceg.setPlaceholderText("")
        self.txt_wgceg.setObjectName("txt_wgceg")
        self.txt_vwgcm_2 = QtWidgets.QLineEdit(self.frame)
        self.txt_vwgcm_2.setGeometry(QtCore.QRect(680, 290, 341, 41))
        self.txt_vwgcm_2.setStyleSheet("QLineEdit{\n"
"\n"
"\n"
"background-color:#fff;\n"
"border: 1px solid #8ec0af;\n"
"border-radius: 6px\n"
"}")
        self.txt_vwgcm_2.setPlaceholderText("")
        self.txt_vwgcm_2.setObjectName("txt_vwgcm_2")
        self.lbl_wgccg = QtWidgets.QLabel(self.frame)
        self.lbl_wgccg.setGeometry(QtCore.QRect(10, 260, 311, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lbl_wgccg.setFont(font)
        self.lbl_wgccg.setStyleSheet("color: black;")
        self.lbl_wgccg.setObjectName("lbl_wgccg")
        self.lbl_wgceg = QtWidgets.QLabel(self.frame)
        self.lbl_wgceg.setGeometry(QtCore.QRect(340, 260, 281, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lbl_wgceg.setFont(font)
        self.lbl_wgceg.setStyleSheet("color: black;")
        self.lbl_wgceg.setObjectName("lbl_wgceg")
        self.lbl_vwgcm_2 = QtWidgets.QLabel(self.frame)
        self.lbl_vwgcm_2.setGeometry(QtCore.QRect(680, 260, 341, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lbl_vwgcm_2.setFont(font)
        self.lbl_vwgcm_2.setStyleSheet("color: black;")
        self.lbl_vwgcm_2.setObjectName("lbl_vwgcm_2")
        self.txt_wocg = QtWidgets.QLineEdit(self.frame)
        self.txt_wocg.setGeometry(QtCore.QRect(10, 370, 211, 41))
        self.txt_wocg.setStyleSheet("QLineEdit{\n"
"\n"
"\n"
"background-color:#fff;\n"
"border: 1px solid #8ec0af;\n"
"border-radius: 6px\n"
"}")
        self.txt_wocg.setPlaceholderText("")
        self.txt_wocg.setObjectName("txt_wocg")
        self.lbl_wocg = QtWidgets.QLabel(self.frame)
        self.lbl_wocg.setGeometry(QtCore.QRect(10, 340, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lbl_wocg.setFont(font)
        self.lbl_wocg.setStyleSheet("color: red;")
        self.lbl_wocg.setObjectName("lbl_wocg")
        self.lbl_wdscg = QtWidgets.QLabel(self.frame)
        self.lbl_wdscg.setGeometry(QtCore.QRect(230, 340, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lbl_wdscg.setFont(font)
        self.lbl_wdscg.setStyleSheet("color: red;")
        self.lbl_wdscg.setObjectName("lbl_wdscg")
        self.txt_wdscg = QtWidgets.QLineEdit(self.frame)
        self.txt_wdscg.setGeometry(QtCore.QRect(230, 370, 221, 41))
        self.txt_wdscg.setStyleSheet("QLineEdit{\n"
"\n"
"\n"
"background-color:#fff;\n"
"border: 1px solid #8ec0af;\n"
"border-radius: 6px\n"
"}")
        self.txt_wdscg.setPlaceholderText("")
        self.txt_wdscg.setObjectName("txt_wdscg")
        self.btn_calculate_sample = QtWidgets.QPushButton(self.frame)
        self.btn_calculate_sample.setGeometry(QtCore.QRect(400, 770, 271, 41))
        self.btn_calculate_sample.setStyleSheet("\n"
"\n"
"QPushButton#btn_calculate_sample{\n"
"\n"
"border:none;\n"
"background-color:#044e42;\n"
"color:white;\n"
"font-size:14px;\n"
"border-radius: 6px;\n"
"transition: background-color 0.5s ease;\n"
"padding:10px;\n"
"text-align:rigth;\n"
"}\n"
"\n"
"QPushButton#btn_calculate_sample:hover{\n"
" background-color: #044e42;\n"
"border-radius: 6px;\n"
"transition: background-color 0.5s ease;\n"
"padding:10px;\n"
"}\n"
"\n"
"QPushButton#btn_calculate_sample:pressed {\n"
" background-color: #044e42;\n"
"border-radius: 6px;\n"
"background-color: #033029;\n"
"padding:10px;\n"
" }\n"
"")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(".\\../../img/check-solid.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_calculate_sample.setIcon(icon1)
        self.btn_calculate_sample.setObjectName("btn_calculate_sample")
        self.txt_wdscg_2 = QtWidgets.QLineEdit(self.frame)
        self.txt_wdscg_2.setGeometry(QtCore.QRect(460, 370, 211, 41))
        self.txt_wdscg_2.setStyleSheet("QLineEdit{\n"
"\n"
"\n"
"background-color:#fff;\n"
"border: 1px solid #8ec0af;\n"
"border-radius: 6px\n"
"}")
        self.txt_wdscg_2.setPlaceholderText("")
        self.txt_wdscg_2.setObjectName("txt_wdscg_2")
        self.lbl_wdscg_2 = QtWidgets.QLabel(self.frame)
        self.lbl_wdscg_2.setGeometry(QtCore.QRect(460, 340, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lbl_wdscg_2.setFont(font)
        self.lbl_wdscg_2.setStyleSheet("color: red;")
        self.lbl_wdscg_2.setObjectName("lbl_wdscg_2")
        self.txt_wdscg_5 = QtWidgets.QLineEdit(self.frame)
        self.txt_wdscg_5.setGeometry(QtCore.QRect(230, 450, 221, 41))
        self.txt_wdscg_5.setStyleSheet("QLineEdit{\n"
"\n"
"\n"
"background-color:#fff;\n"
"border: 1px solid #8ec0af;\n"
"border-radius: 6px\n"
"}")
        self.txt_wdscg_5.setPlaceholderText("")
        self.txt_wdscg_5.setObjectName("txt_wdscg_5")
        self.txt_wdscg_6 = QtWidgets.QLineEdit(self.frame)
        self.txt_wdscg_6.setGeometry(QtCore.QRect(10, 450, 211, 41))
        self.txt_wdscg_6.setStyleSheet("QLineEdit{\n"
"\n"
"\n"
"background-color:#fff;\n"
"border: 1px solid #8ec0af;\n"
"border-radius: 6px\n"
"}")
        self.txt_wdscg_6.setPlaceholderText("")
        self.txt_wdscg_6.setObjectName("txt_wdscg_6")
        self.txt_wocg_3 = QtWidgets.QLineEdit(self.frame)
        self.txt_wocg_3.setGeometry(QtCore.QRect(680, 370, 341, 41))
        self.txt_wocg_3.setStyleSheet("QLineEdit{\n"
"\n"
"\n"
"background-color:#fff;\n"
"border: 1px solid #8ec0af;\n"
"border-radius: 6px\n"
"}")
        self.txt_wocg_3.setPlaceholderText("")
        self.txt_wocg_3.setObjectName("txt_wocg_3")
        self.lbl_wdscg_5 = QtWidgets.QLabel(self.frame)
        self.lbl_wdscg_5.setGeometry(QtCore.QRect(230, 420, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lbl_wdscg_5.setFont(font)
        self.lbl_wdscg_5.setStyleSheet("color: red;")
        self.lbl_wdscg_5.setObjectName("lbl_wdscg_5")
        self.lbl_wocg_3 = QtWidgets.QLabel(self.frame)
        self.lbl_wocg_3.setGeometry(QtCore.QRect(680, 340, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lbl_wocg_3.setFont(font)
        self.lbl_wocg_3.setStyleSheet("color: red;")
        self.lbl_wocg_3.setObjectName("lbl_wocg_3")
        self.lbl_wdscg_6 = QtWidgets.QLabel(self.frame)
        self.lbl_wdscg_6.setGeometry(QtCore.QRect(10, 420, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lbl_wdscg_6.setFont(font)
        self.lbl_wdscg_6.setStyleSheet("color: red;")
        self.lbl_wdscg_6.setObjectName("lbl_wdscg_6")
        self.txt_wocg_4 = QtWidgets.QLineEdit(self.frame)
        self.txt_wocg_4.setGeometry(QtCore.QRect(460, 450, 211, 41))
        self.txt_wocg_4.setStyleSheet("QLineEdit{\n"
"\n"
"\n"
"background-color:#fff;\n"
"border: 1px solid #8ec0af;\n"
"border-radius: 6px\n"
"}")
        self.txt_wocg_4.setPlaceholderText("")
        self.txt_wocg_4.setObjectName("txt_wocg_4")
        self.txt_wdscg_7 = QtWidgets.QLineEdit(self.frame)
        self.txt_wdscg_7.setGeometry(QtCore.QRect(680, 450, 341, 41))
        self.txt_wdscg_7.setStyleSheet("QLineEdit{\n"
"\n"
"\n"
"background-color:#fff;\n"
"border: 1px solid #8ec0af;\n"
"border-radius: 6px\n"
"}")
        self.txt_wdscg_7.setPlaceholderText("")
        self.txt_wdscg_7.setObjectName("txt_wdscg_7")
        self.txt_wdscg_8 = QtWidgets.QLineEdit(self.frame)
        self.txt_wdscg_8.setGeometry(QtCore.QRect(680, 530, 341, 41))
        self.txt_wdscg_8.setStyleSheet("QLineEdit{\n"
"\n"
"\n"
"background-color:#fff;\n"
"border: 1px solid #8ec0af;\n"
"border-radius: 6px\n"
"}")
        self.txt_wdscg_8.setPlaceholderText("")
        self.txt_wdscg_8.setObjectName("txt_wdscg_8")
        self.lbl_wdscg_7 = QtWidgets.QLabel(self.frame)
        self.lbl_wdscg_7.setGeometry(QtCore.QRect(230, 500, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lbl_wdscg_7.setFont(font)
        self.lbl_wdscg_7.setStyleSheet("color: red;")
        self.lbl_wdscg_7.setObjectName("lbl_wdscg_7")
        self.lbl_wdscg_8 = QtWidgets.QLabel(self.frame)
        self.lbl_wdscg_8.setGeometry(QtCore.QRect(680, 500, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lbl_wdscg_8.setFont(font)
        self.lbl_wdscg_8.setStyleSheet("color: red;")
        self.lbl_wdscg_8.setObjectName("lbl_wdscg_8")
        self.txt_wdscg_9 = QtWidgets.QLineEdit(self.frame)
        self.txt_wdscg_9.setGeometry(QtCore.QRect(460, 530, 211, 41))
        self.txt_wdscg_9.setStyleSheet("QLineEdit{\n"
"\n"
"\n"
"background-color:#fff;\n"
"border: 1px solid #8ec0af;\n"
"border-radius: 6px\n"
"}")
        self.txt_wdscg_9.setPlaceholderText("")
        self.txt_wdscg_9.setObjectName("txt_wdscg_9")
        self.lbl_wdscg_9 = QtWidgets.QLabel(self.frame)
        self.lbl_wdscg_9.setGeometry(QtCore.QRect(460, 500, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lbl_wdscg_9.setFont(font)
        self.lbl_wdscg_9.setStyleSheet("color: red;")
        self.lbl_wdscg_9.setObjectName("lbl_wdscg_9")
        self.txt_wdscg_10 = QtWidgets.QLineEdit(self.frame)
        self.txt_wdscg_10.setGeometry(QtCore.QRect(230, 530, 221, 41))
        self.txt_wdscg_10.setStyleSheet("QLineEdit{\n"
"\n"
"\n"
"background-color:#fff;\n"
"border: 1px solid #8ec0af;\n"
"border-radius: 6px\n"
"}")
        self.txt_wdscg_10.setPlaceholderText("")
        self.txt_wdscg_10.setObjectName("txt_wdscg_10")
        self.lbl_wocg_4 = QtWidgets.QLabel(self.frame)
        self.lbl_wocg_4.setGeometry(QtCore.QRect(460, 420, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lbl_wocg_4.setFont(font)
        self.lbl_wocg_4.setStyleSheet("color: red;")
        self.lbl_wocg_4.setObjectName("lbl_wocg_4")
        self.lbl_wocg_5 = QtWidgets.QLabel(self.frame)
        self.lbl_wocg_5.setGeometry(QtCore.QRect(10, 500, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lbl_wocg_5.setFont(font)
        self.lbl_wocg_5.setStyleSheet("color: red;")
        self.lbl_wocg_5.setObjectName("lbl_wocg_5")
        self.lbl_wdscg_10 = QtWidgets.QLabel(self.frame)
        self.lbl_wdscg_10.setGeometry(QtCore.QRect(680, 420, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lbl_wdscg_10.setFont(font)
        self.lbl_wdscg_10.setStyleSheet("color: red;")
        self.lbl_wdscg_10.setObjectName("lbl_wdscg_10")
        self.txt_wocg_5 = QtWidgets.QLineEdit(self.frame)
        self.txt_wocg_5.setGeometry(QtCore.QRect(10, 530, 211, 41))
        self.txt_wocg_5.setStyleSheet("QLineEdit{\n"
"\n"
"\n"
"background-color:#fff;\n"
"border: 1px solid #8ec0af;\n"
"border-radius: 6px\n"
"}")
        self.txt_wocg_5.setPlaceholderText("")
        self.txt_wocg_5.setObjectName("txt_wocg_5")
        self.lbl_wocg_6 = QtWidgets.QLabel(self.frame)
        self.lbl_wocg_6.setGeometry(QtCore.QRect(10, 580, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lbl_wocg_6.setFont(font)
        self.lbl_wocg_6.setStyleSheet("color: red;")
        self.lbl_wocg_6.setObjectName("lbl_wocg_6")
        self.txt_wocg_6 = QtWidgets.QLineEdit(self.frame)
        self.txt_wocg_6.setGeometry(QtCore.QRect(10, 610, 211, 41))
        self.txt_wocg_6.setStyleSheet("QLineEdit{\n"
"\n"
"\n"
"background-color:#fff;\n"
"border: 1px solid #8ec0af;\n"
"border-radius: 6px\n"
"}")
        self.txt_wocg_6.setPlaceholderText("")
        self.txt_wocg_6.setObjectName("txt_wocg_6")
        self.txt_wdscg_11 = QtWidgets.QLineEdit(self.frame)
        self.txt_wdscg_11.setGeometry(QtCore.QRect(230, 610, 221, 41))
        self.txt_wdscg_11.setStyleSheet("QLineEdit{\n"
"\n"
"\n"
"background-color:#fff;\n"
"border: 1px solid #8ec0af;\n"
"border-radius: 6px\n"
"}")
        self.txt_wdscg_11.setPlaceholderText("")
        self.txt_wdscg_11.setObjectName("txt_wdscg_11")
        self.lbl_wdscg_11 = QtWidgets.QLabel(self.frame)
        self.lbl_wdscg_11.setGeometry(QtCore.QRect(230, 580, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lbl_wdscg_11.setFont(font)
        self.lbl_wdscg_11.setStyleSheet("color: red;")
        self.lbl_wdscg_11.setObjectName("lbl_wdscg_11")
        self.txt_wdscg_21 = QtWidgets.QLineEdit(self.frame)
        self.txt_wdscg_21.setGeometry(QtCore.QRect(460, 610, 211, 41))
        self.txt_wdscg_21.setStyleSheet("QLineEdit{\n"
"\n"
"\n"
"background-color:#fff;\n"
"border: 1px solid #8ec0af;\n"
"border-radius: 6px\n"
"}")
        self.txt_wdscg_21.setPlaceholderText("")
        self.txt_wdscg_21.setObjectName("txt_wdscg_21")
        self.lbl_wdscg_21 = QtWidgets.QLabel(self.frame)
        self.lbl_wdscg_21.setGeometry(QtCore.QRect(460, 580, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lbl_wdscg_21.setFont(font)
        self.lbl_wdscg_21.setStyleSheet("color: red;")
        self.lbl_wdscg_21.setObjectName("lbl_wdscg_21")
        self.lbl_wdscg_22 = QtWidgets.QLabel(self.frame)
        self.lbl_wdscg_22.setGeometry(QtCore.QRect(680, 580, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lbl_wdscg_22.setFont(font)
        self.lbl_wdscg_22.setStyleSheet("color: red;")
        self.lbl_wdscg_22.setObjectName("lbl_wdscg_22")
        self.txt_wdscg_22 = QtWidgets.QLineEdit(self.frame)
        self.txt_wdscg_22.setGeometry(QtCore.QRect(680, 610, 341, 41))
        self.txt_wdscg_22.setStyleSheet("QLineEdit{\n"
"\n"
"\n"
"background-color:#fff;\n"
"border: 1px solid #8ec0af;\n"
"border-radius: 6px\n"
"}")
        self.txt_wdscg_22.setPlaceholderText("")
        self.txt_wdscg_22.setObjectName("txt_wdscg_22")
        self.txt_wdscg_34 = QtWidgets.QLineEdit(self.frame)
        self.txt_wdscg_34.setGeometry(QtCore.QRect(350, 690, 321, 41))
        self.txt_wdscg_34.setStyleSheet("QLineEdit{\n"
"\n"
"\n"
"background-color:#fff;\n"
"border: 1px solid #8ec0af;\n"
"border-radius: 6px\n"
"}")
        self.txt_wdscg_34.setPlaceholderText("")
        self.txt_wdscg_34.setObjectName("txt_wdscg_34")
        self.lbl_wocg_17 = QtWidgets.QLabel(self.frame)
        self.lbl_wocg_17.setGeometry(QtCore.QRect(10, 660, 331, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lbl_wocg_17.setFont(font)
        self.lbl_wocg_17.setStyleSheet("color: red;")
        self.lbl_wocg_17.setObjectName("lbl_wocg_17")
        self.txt_wocg_17 = QtWidgets.QLineEdit(self.frame)
        self.txt_wocg_17.setGeometry(QtCore.QRect(10, 690, 321, 41))
        self.txt_wocg_17.setStyleSheet("QLineEdit{\n"
"\n"
"\n"
"background-color:#fff;\n"
"border: 1px solid #8ec0af;\n"
"border-radius: 6px\n"
"}")
        self.txt_wocg_17.setPlaceholderText("")
        self.txt_wocg_17.setObjectName("txt_wocg_17")
        self.lbl_wdscg_34 = QtWidgets.QLabel(self.frame)
        self.lbl_wdscg_34.setGeometry(QtCore.QRect(350, 660, 291, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lbl_wdscg_34.setFont(font)
        self.lbl_wdscg_34.setStyleSheet("color: red;")
        self.lbl_wdscg_34.setObjectName("lbl_wdscg_34")
        self.txt_wdscg_35 = QtWidgets.QLineEdit(self.frame)
        self.txt_wdscg_35.setGeometry(QtCore.QRect(690, 690, 331, 41))
        self.txt_wdscg_35.setStyleSheet("QLineEdit{\n"
"\n"
"\n"
"background-color:#fff;\n"
"border: 1px solid #8ec0af;\n"
"border-radius: 6px\n"
"}")
        self.txt_wdscg_35.setPlaceholderText("")
        self.txt_wdscg_35.setObjectName("txt_wdscg_35")
        self.lbl_wdscg_35 = QtWidgets.QLabel(self.frame)
        self.lbl_wdscg_35.setGeometry(QtCore.QRect(690, 660, 291, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lbl_wdscg_35.setFont(font)
        self.lbl_wdscg_35.setStyleSheet("color: red;")
        self.lbl_wdscg_35.setObjectName("lbl_wdscg_35")
        self.lbl_wocg_18 = QtWidgets.QLabel(self.frame)
        self.lbl_wocg_18.setGeometry(QtCore.QRect(10, 740, 381, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lbl_wocg_18.setFont(font)
        self.lbl_wocg_18.setStyleSheet("color: red;")
        self.lbl_wocg_18.setObjectName("lbl_wocg_18")
        self.txt_wocg_18 = QtWidgets.QLineEdit(self.frame)
        self.txt_wocg_18.setGeometry(QtCore.QRect(10, 770, 381, 41))
        self.txt_wocg_18.setStyleSheet("QLineEdit{\n"
"\n"
"\n"
"background-color:#fff;\n"
"border: 1px solid #8ec0af;\n"
"border-radius: 6px\n"
"}")
        self.txt_wocg_18.setPlaceholderText("")
        self.txt_wocg_18.setObjectName("txt_wocg_18")
        self.btn_add_sample = QtWidgets.QPushButton(self.frame)
        self.btn_add_sample.setGeometry(QtCore.QRect(690, 770, 331, 41))
        self.btn_add_sample.setStyleSheet("\n"
"\n"
"QPushButton#btn_add_sample{\n"
"\n"
"border:none;\n"
"background-color:#044e42;\n"
"color:white;\n"
"font-size:14px;\n"
"border-radius: 6px;\n"
"transition: background-color 0.5s ease;\n"
"padding:10px;\n"
"text-align:rigth;\n"
"}\n"
"\n"
"QPushButton#btn_add_sample:hover{\n"
" background-color: #044e42;\n"
"border-radius: 6px;\n"
"transition: background-color 0.5s ease;\n"
"padding:10px;\n"
"}\n"
"\n"
"QPushButton#btn_add_sample:pressed {\n"
" background-color: #044e42;\n"
"border-radius: 6px;\n"
"background-color: #033029;\n"
"padding:10px;\n"
" }\n"
"")
        self.btn_add_sample.setIcon(icon1)
        self.btn_add_sample.setObjectName("btn_add_sample")
        self.lbl_wdscg_35.raise_()
        self.lbl_wdscg_34.raise_()
        self.lbl_wdscg_21.raise_()
        self.lbl_wdscg_11.raise_()
        self.lbl_wdscg_7.raise_()
        self.lbl_wdscg_9.raise_()
        self.lbl_wocg_4.raise_()
        self.lbl_wocg_5.raise_()
        self.lbl_wdscg_10.raise_()
        self.lbl_wdscg_8.raise_()
        self.lbl_wdscg_5.raise_()
        self.lbl_wdscg_6.raise_()
        self.lbl_wocg_3.raise_()
        self.lbl_wdscg_2.raise_()
        self.lbl_wocg.raise_()
        self.lbl_vwgcm_2.raise_()
        self.lbl_wgceg.raise_()
        self.lbl_wgccg.raise_()
        self.lbl_vwgcm.raise_()
        self.lbl_wwag.raise_()
        self.lbl_wfrcbswg.raise_()
        self.lbl_wsg.raise_()
        self.lbl_wercb.raise_()
        self.frame_2.raise_()
        self.frame_3.raise_()
        self.frame_9.raise_()
        self.line_2.raise_()
        self.lbl_weigth_cb_sample_gms.raise_()
        self.txt_wfrcb_sample_gms.raise_()
        self.txt_wercb.raise_()
        self.txt_wsg.raise_()
        self.txt_wfrcbsw.raise_()
        self.txt_wwag.raise_()
        self.txt_vwgcm.raise_()
        self.txt_wgccg.raise_()
        self.txt_wgceg.raise_()
        self.txt_vwgcm_2.raise_()
        self.txt_wocg.raise_()
        self.lbl_wdscg.raise_()
        self.txt_wdscg.raise_()
        self.btn_calculate_sample.raise_()
        self.txt_wdscg_2.raise_()
        self.txt_wdscg_5.raise_()
        self.txt_wdscg_6.raise_()
        self.txt_wocg_3.raise_()
        self.txt_wocg_4.raise_()
        self.txt_wdscg_7.raise_()
        self.txt_wdscg_8.raise_()
        self.txt_wdscg_9.raise_()
        self.txt_wdscg_10.raise_()
        self.txt_wocg_5.raise_()
        self.lbl_wocg_6.raise_()
        self.txt_wocg_6.raise_()
        self.txt_wdscg_11.raise_()
        self.txt_wdscg_21.raise_()
        self.lbl_wdscg_22.raise_()
        self.txt_wdscg_22.raise_()
        self.txt_wdscg_34.raise_()
        self.lbl_wocg_17.raise_()
        self.txt_wocg_17.raise_()
        self.txt_wdscg_35.raise_()
        self.lbl_wocg_18.raise_()
        self.txt_wocg_18.raise_()
        self.btn_add_sample.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1050, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Dashboard"))
        self.lbl_form_tittle.setText(_translate("MainWindow", "Average Dry cuttings gms/kg"))
        self.lbl_form_text.setText(_translate("MainWindow", "Fill in the fields to obtain the sample results"))
        self.lbl_weigth_cb_sample_gms.setText(_translate("MainWindow", "Synthetic SG"))
        self.lbl_wercb.setText(_translate("MainWindow", "ROP At Time Of Sample"))
        self.lbl_wsg.setText(_translate("MainWindow", "Weight Empty Retort Cell + Body"))
        self.lbl_wfrcbswg.setText(_translate("MainWindow", "Weight Filled Retort Cell + Body + Sample gms"))
        self.lbl_wwag.setText(_translate("MainWindow", "Weight Filled Retort Cell + Body + Sample + water gms"))
        self.lbl_vwgcm.setText(_translate("MainWindow", "Weight Graduated Cylinder - Empty gms"))
        self.lbl_wgccg.setText(_translate("MainWindow", "Weight Graduated Cylinder + Condensate gms"))
        self.lbl_wgceg.setText(_translate("MainWindow", "Volume of Water in graduated cylinder mls"))
        self.lbl_vwgcm_2.setText(_translate("MainWindow", "Weight Retort Cell complete after retort cooled gms"))
        self.lbl_wocg.setText(_translate("MainWindow", "Weight of Sample gms"))
        self.lbl_wdscg.setText(_translate("MainWindow", "Weight of water added gms"))
        self.btn_calculate_sample.setText(_translate("MainWindow", "Calculate "))
        self.lbl_wdscg_2.setText(_translate("MainWindow", "Volume of Sample mls"))
        self.lbl_wdscg_5.setText(_translate("MainWindow", "Weight Oil - calc gms"))
        self.lbl_wocg_3.setText(_translate("MainWindow", "Density Sample SG"))
        self.lbl_wdscg_6.setText(_translate("MainWindow", "Weight Condensate gms"))
        self.lbl_wdscg_7.setText(_translate("MainWindow", "% Oil by volume"))
        self.lbl_wdscg_8.setText(_translate("MainWindow", "Weight Dry Solids - calculated gms"))
        self.lbl_wdscg_9.setText(_translate("MainWindow", "% Water by volume "))
        self.lbl_wocg_4.setText(_translate("MainWindow", "VOL Oil mls"))
        self.lbl_wocg_5.setText(_translate("MainWindow", "Weight Dry Solids - actual gms"))
        self.lbl_wdscg_10.setText(_translate("MainWindow", "Weight Water In Sample gms"))
        self.lbl_wocg_6.setText(_translate("MainWindow", "% Solids by volume"))
        self.lbl_wdscg_11.setText(_translate("MainWindow", "% Oil by weight"))
        self.lbl_wdscg_21.setText(_translate("MainWindow", "% Water by weight "))
        self.lbl_wdscg_22.setText(_translate("MainWindow", "% Solids by weight"))
        self.lbl_wocg_17.setText(_translate("MainWindow", "SOC, Weight of Synthetic on Dry Cuttings gms/kg"))
        self.lbl_wdscg_34.setText(_translate("MainWindow", "OOC, Weight of Oil on Wet Cuttings gms/kg"))
        self.lbl_wdscg_35.setText(_translate("MainWindow", "Mud Weight PPG  "))
        self.lbl_wocg_18.setText(_translate("MainWindow", "Accuracy check ( If outside 95 to 105 range re-run retort)"))
        self.btn_add_sample.setText(_translate("MainWindow", " Add Sample"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
